### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Joelifer123** [FTBTeam/FTB-Academy#101]
* **Modpack Version**: 1.0.0

* **Issue**: The modpack crashes every time I open it, I believe it is to do with codechickenlib. I have tried a few things but nothing works

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/c158d628

* **Is it Repeatable?**: I can repeat it by trying to open the pack

* **Mod/s Affected**: codechickenlib seems to be causing all the problems

* **Known Fix**: I do not

**Comment by Sunekaer** [comment]
Please test with https://www.feed-the-beast.com/projects/ftb-academy/files/2792364
