### ISSUE TITLE
Server errors and crashes

### ISSUE THREAD

**Issue by rkrick99** [FTBTeam/FTB-Academy#102]
[latest.log](https://github.com/FTBTeam/FTB-Academy/files/3570776/latest.log)

* **Modpack Version**: 1.0

* **Issue**: crashed while playing
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: errorslisted in logs every time server is loaded

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
From logs your server loads without crash, please the errors to the mod authors
