### ISSUE TITLE
Can't download the modpack

### ISSUE THREAD

**Issue by bigesser** [FTBTeam/FTB-Academy#105]
* **Modpack Version**:  Version Release 20/8/19

* **Issue**: i can't download the modpack no matter what i do

* **Link to Log or Crash File Paste**: Timeout attempting to download: https://edge.forgecdn.net/files/2766/338/FTBAcademy-1.0.0-1.12.2.zip

* **Is it Repeatable?**: yes everytime i try

**Comment by danieldides** [comment]
The link is working for me both through a VPN and directly. Are you still seeing this? Perhaps it was just unlucky timing yesterday.

**Comment by aaronhowser1** [comment]
Are you on a Mac by change? Apparently a lot of Mac users are having issues like this

**Comment by Sunekaer** [comment]
Link works fine for me, its either your network or pc blocking the download or something wrong with the launch, please contact twitch or which launcher your using
