### ISSUE TITLE
Change the /clear command to /minecraft:clear

### ISSUE THREAD

**Issue by xElementzx** [FTBTeam/FTB-Academy#106]
* **Modpack Version**: 1.0.0

* **Issue**: /clear in customized servers running SpongeForge and Nucleus doesn't clear out things from your inventory as nucleus changes the /clear command

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: FTB Quests?

* **Known Fix**: setting the command to be /minecraft:clear forcing it to use the minecraft variant of the clear command would fix this issue.

**Comment by aaronhowser1** [comment]
We don't support SpongeForge or any plugins for it. This is a problem with Nucleus for changing vanilla commands. Adding `minecraft:` to a command doesn't work, the game doesn't see `/minecraft:clear` as a command.
