### ISSUE TITLE
Playing Lan: Placing Stabalized Spawner disconnects all other players and they can't join anymore

### ISSUE THREAD

**Issue by NiklasRei** [FTBTeam/FTB-Academy#107]
* **Modpack Version**:  3.1.0

* **Issue**: When placing the Stabalized spawner or when the Stabalized spawner is already placed. All other (except the main player, lan!) are getting disconnected. They can't join until the spawner is destroyed.

* **Link to Log or Crash File Paste**: The game does not crash, just all other players are getting disconnected and can't rejoin

* **Is it Repeatable?**: yes, even after reinstall

* **Mod/s Affected**: Stabalized spawner from Draconic Evolution

* **Known Fix**: non - destroy spawner and don't place them :(

**Comment by Sunekaer** [comment]
Need log file to check for errors
