### ISSUE TITLE
Stuck in questing progress

### ISSUE THREAD

**Issue by NotTete** [FTBTeam/FTB-Academy#109]
* **Modpack Version**: 1.0.0
* **Issue**: When you change from team you can't progress because when the quests resets you have to make the tutorial quests than request enter in a room for example and are impossible to make once you graduate.

* **Link to Log or Crash File Paste**: No one

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: Ftb Quest, Ftb Utilities

* **Known Fix**: I don't know

**Comment by aaronhowser1** [comment]
The first chapter will automatically complete if you reset your quest progress in the Overworld

**Comment by jcrites** [comment]
I ran into this problem in my first run through FTB Academy. I took the upgrade item out of the wood chest before interacting with the other chests, causing me to become stuck.

**Comment by aaronhowser1** [comment]
@jcrites there's an issue for it [here](https://github.com/FTBTeam/FTB-Academy/issues/175)
