### ISSUE TITLE
why is there no tinkers construct tutorial in the school

### ISSUE THREAD

**Issue by CobotGamer** [FTBTeam/FTB-Academy#11]
* **newist**: 

* **no tutorial for tinkers construct**: 

 

* **yes?**: 

* **tinkers construct**: 

* **add a tutorial to the school**:

**Comment by Sunekaer** [comment]
There is in overworld, after the school.
If you think there should be in school, please tell why and how that would be better then in overworld where your gonna use the,

**Comment by aaronhowser1** [comment]
There's 4 quests and a lengthy chapter in the guide on Tinkers Construct
