### ISSUE TITLE
Ender tank not working properly

### ISSUE THREAD

**Issue by godlifed** [FTBTeam/FTB-Academy#110]
* **Modpack Version**: 1.0.0

* **Issue**: ender tank only fills once 
I have an ender tank being filled with lava in the nether and one in the overworld, the ender tank fills up once when i place it just fine, but when that lava is used the tank doesnt refill.
Also tried with water in the from overworld to the overworld and it didn't work

* **Is it Repeatable?**: everytime

(so i haven't played with modded minecraft for a while... so the only reason would be if the ender tanks would have been nerfed, and if they were sorry)

**Comment by aaronhowser1** [comment]
The pump has to be chunkloaded for it to refill while you aren't there.

Also, hold sneak and look at the top of the screen, see if it's empty. It might have like, 1mB of Oil or something in it.
