### ISSUE TITLE
Dependency missing for FTB Academy Mod

### ISSUE THREAD

**Issue by Nezmin2** [FTBTeam/FTB-Academy#116]
* **Modpack Version**:  1.0.0

* **Issue**: Updated mod to version 1.0.3.48 and recieved a missing dependency kubejs message 

* **Is it Repeatable?**:  Yes 

* **Known Fix**:  Unknown

**Comment by aaronhowser1** [comment]
This is not a problem with the modpack, you changed it.

The new version of FTBAM is for Academy 1.1.0, when that comes out. It will have KubeJS.
