### ISSUE TITLE
Astral Sorcery Quest Not Getting Recognized

### ISSUE THREAD

**Issue by S2Kreative** [FTBTeam/FTB-Academy#119]
* **Modpack Version**: 1.0

* **Issue**: Starlight Redirection Lens quest is not completed after making said item

* **Link to Log or Crash File Paste**: There is no crash

* **Is it Repeatable?**: Someone else on the MineTogether chat said he was having the same issue

* **Mod/s Affected**: Astral Sorcery

* **Known Fix**: I don't know

**Comment by aaronhowser1** [comment]
#70, already fixed for next update
