### ISSUE TITLE
Instrumental mobs crashed the nether. 

### ISSUE THREAD

**Issue by stutteringdude** [FTBTeam/FTB-Academy#12]
* **1.0.0**: >

* **While exploring the nether. A crashed happened that closed the client. I attempted to reload and it to not start back up. it was the instrumental mobs pack that caused the issues. I disabled it and it started up fine. **: 

* **https://paste.feed-the-beast.com/view/9bee48eb: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Sunekaer** [comment]
Please update Instrumental mobs to this version and see if you still have the issue
https://www.curseforge.com/minecraft/mc-mods/instrumental-mobs/files/2767795
