### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by peru909** [FTBTeam/FTB-Academy#121]
I have a friend who would like to start playing with the mods, but unfortunately, he doesn't know English.
Is there a way to translate the quests into Italian?

**Comment by aaronhowser1** [comment]
If someone translates it into Italian, then yes :P

See [here](https://github.com/FTBTeam/FTB-Academy) for how to do that

**Comment by peru909** [comment]
So Cool, I'm going to work on it;

Thank you very much
