### ISSUE TITLE
Can't access items in Refined Storage

### ISSUE THREAD

**Issue by iLazer** [FTBTeam/FTB-Academy#122]
FTB Academy V1.0.0

I was searching for something in refined storage when I re-entered into the crafting grid and all my items were gone, but everything else worked great. the Search bar nor any of the settings changed anything, dropping items into it would just "Delete Them". And rebuilding the system did nothing. Yes, it did have enough power 😒

Repeatable: No

Mod: Refined Storage

Fix: Reboot FTB

**Comment by iLazer** [comment]
I found a solution. By rebooting FTB, you can fix this problem. I tried this without rebooting FTB and it didn't work so I thought this wasn't possible. Anyways, This still should be fixed so other people aren't set on a wild goose chase like I was.

**Comment by aaronhowser1** [comment]
No idea what would cause this. Report it to the Refined Storage issue tracker.
