### ISSUE TITLE
Ghast spawning issue

### ISSUE THREAD

**Issue by TheDarkAndroid** [FTBTeam/FTB-Academy#123]
* **Modpack Version**: 1.0.0 
* **Issue**: Ghasts aren't spawning in the Nether
* **Is it Repeatable?**: Yes

**Comment by Ozzymud** [comment]
https://github.com/FTBTeam/FTB-Academy/issues/44

**Comment by aaronhowser1** [comment]
You can disable Foxhounds from Quark to fix this temporarily
