### ISSUE TITLE
Title screen background spazzing out

### ISSUE THREAD

**Issue by Tobo64** [FTBTeam/FTB-Academy#124]
* **Modpack Version**: 1.0.0

* **Issue**: Everytime when I start up the pack and get to the title screen the background starts spazzing out. just like when you move your mouse in all directions with really high sensitivity. This would have been not that bad if it weren't that sometimes my screen starts spazzing out when I walk too. when I am standing in place everything is okay. but when I walk in any direction the whole screen spazzes out for a good 5 seconds before turning normal. 
To make it more clear I made a quick video showing the title screen (link to the video: https://youtu.be/I8gYdzgr_fE   )

* **Is it Repeatable?**: It happens to me everytime I start it up. it started today. Before that I had no problems

**Comment by aaronhowser1** [comment]
Do you happen to use an AMD graphics card? Try installing VanillaFix, it fixes a problem with AMD cards.

**Comment by Tobo64** [comment]
I have an Intel graphics card. No AMD. I can still try it though

**Comment by Sunekaer** [comment]
try reinstalling the pack and see if it happens
