### ISSUE TITLE
Quest: Filled with power ... Already have a charger

### ISSUE THREAD

**Issue by Ozzymud** [FTBTeam/FTB-Academy#125]
Modpack Version: 1.0.0

The Pitiful Generator made in a previous quest will already charge items.

Maybe make mention that the new options will charge things much faster as the Pitiful Generator only has an internal buffer of 100k RF.

Even then, I haven't found a huge need to complete the filled with power quest as the Pitiful has charged everything I've needed it to... toss item in, do something else... profit.

**Comment by aaronhowser1** [comment]
Oh really? I had no idea it could also charge items. Will mention in the quest.
