### ISSUE TITLE
Future issue: Actually Additions 1.12.2-r150

### ISSUE THREAD

**Issue by Ozzymud** [FTBTeam/FTB-Academy#126]
Just as a heads up on the Greenhouse Glass quest... It currently mentions the glass is stackable as it indeed is. The latest release of Actually Additions (1.12.2-r150) has the following in the changelog:  

•Greenhouse glass does not stack. 

http://ellpeck.de/actaddchangelog

**Comment by aaronhowser1** [comment]
F, will change text. Thanks
