### ISSUE TITLE
Add Simply Jetpacks 2

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Academy#128]
There are flight options, but they are mostly creative flight and endgame and all (except Draconic Chestplate) are magic. Jetpacks would be really nice early tech flight. That mod doesn't require EIO afaik

**Comment by Dakedres** [comment]
It's also just, a super widespread mod you should have some idea how to use

**Comment by Samario1** [comment]
yeah

**Comment by aaronhowser1** [comment]
yeah

**Comment by f4b14nnn** [comment]
definitely think simply jetpacks 2 should be added

**Comment by enescaglayan** [comment]
Yes please, I need a way to find a fast way to get astral sorcery white crystal thingy a way that is basic and requires only some work.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/68739835-6deebe80-05af-11ea-86a4-2a1f9155a471.png)
