### ISSUE TITLE
Caught exception from MineTogetherServer

### ISSUE THREAD

**Issue by Calcaholic** [FTBTeam/FTB-Academy#129]
Whenever I start my singleplayer world with the MineTogether mod included, my game will crash with the message "The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineTogetherServer (minetogetherserver);

Pastebin of crash report : https://pastebin.com/PUPbAbU6

**Comment by Sunekaer** [comment]
Seem that the file has been corrupted or overwritten with a blank file.
I would recommend you restore the Minecraft\Instances\FTB Academy\config\minetogether.cfg from the link below to fix the issue.

https://s1.sunekaer.com/files/minetogether.cfg
