### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by davideagle89** [FTBTeam/FTB-Academy#13]
* **Modpack Version**:  FTB Acadamy 1.12.2 8/20/2019 version

* **Issue**:  I received this message: "Access to the path "/var/folders/md/7lmn3srd19n5_qmlkm2h12gw0000gn/T/Curse Client/C564A743784C4515B2ED3822631280D0/5/manifest.json" or "/Users/myuser/Twitch/Minecraft/Instances/FTB Academy/manifest.json" is denied."

* **Link to Log or Crash File Paste**: no link

* **Is it Repeatable?**: every time

* **Mod/s Affected**: n/a

* **Known Fix**: n/a

**Comment by diego898** [comment]
This is the same problem as #7 and #9, both of which are now closed. I commented the following in https://github.com/FTBTeam/FTB-Academy/issues/7#issuecomment-524413545: 

---

> I went searching in both of those paths for that file and that file does not exist there. 
>
> My error message: `Access to the path "/var/folders/g2/7_gg0_851rb_7qdyjmm_gr4m0000gn/T/Curse Client/6592213BAB9345C58FDCB5B0A7B681BC/2/manifest.json" or "/Users/myname/Twitch/Minecraft/Instances/FTB Academy/manifest.json" is denied.`
> 
> 
> At`/var/folders/.../2/`:
> ```
> find . -iname "manifest*"
> ./overrides/config/brandon3055/ProjectIntelligence/DocUpdater/manifest.json
> ./overrides/config/brandon3055/ProjectIntelligence/manifest.json
> ```
> 
> Since this was my first modpack, `/Users/.../Twitch/Minecraft/Instances/` is empty. 
> 
> Restarting twitch, and my computer, did not fix this problem. 
> 
> I was able to succesfully install FTB Ultimate Reloaded. After doing so I have:
> ```
> find . -iname "manifest.json"
> ./FTB Ultimate Reloaded/manifest.json
> ```
> which is expected. 
> 
> I think this is only a problem when installing this mod!

**Comment by Sunekaer** [comment]
The thing is I can't just upload a new export with this fix, due to how we release packs.
ill talk with Twitch and try to have a fix out start of next week

**Comment by wugmump** [comment]
I also have this problem. The file does not exist in either location. Also on a Mac.

**Comment by Sunekaer** [comment]
Pack

**Comment by Sunekaer** [comment]
or launcher

**Comment by Sunekaer** [comment]
i dont know

**Comment by ventolin** [comment]
I ran into this issue with MultiMC on a mac, and then I followed the suggestion here: https://github.com/FTBTeam/FTB-Academy/issues/26#issuecomment-524553482 and that fixed the issue for me.

**Comment by diego898** [comment]
@ventolin Im using the twitch launcher - how do I find the manifest.json its referring to?

**Comment by wugmump** [comment]
Alas, I have the same issue. The manifest.json file is missing from both file locations named.

**Comment by ventolin** [comment]
It's in the modpack's zip file. I just unzipped it, edited the manifest.json, and zipped it back up, then  imported the zip into MultiMC. I don't know anything about other launchers.

**Comment by aaronhowser1** [comment]
Appears to be an issue with Macs?

**Comment by Sunekaer** [comment]
ZIPs have a thing called ExtraAttributes which unix systems use to set permissions on the file
That was not being set in the zip. So on mac it was unziping without read perms

**Comment by Sunekaer** [comment]
it should be fixed now, you might need to redownload the zip
