### ISSUE TITLE
Add Unlimited Chisel Works

### ISSUE THREAD

**Issue by Dakedres** [FTBTeam/FTB-Academy#130]
[Unlimited Chisel Works](https://www.curseforge.com/minecraft/mc-mods/unlimited-chisel-works) is a mod by Asie which adds procedurely generated Chisel variants of many blocks from other mods, I feel it's a very simple addition that would add a lot to the building content of the modpack while not being too difficult to implement. All you'd need to do is notify of the mod's presence in the Guide so that users know that Chisel on it's own doesn't usually have such a vast amount of support.

**Comment by Sunekaer** [comment]
Wont be added in this pack, it is in Builders Paradise if you want to play with it
