### ISSUE TITLE
I Can't transfer my 1.0.0 world over to 1.1.0

### ISSUE THREAD

**Issue by SupaSourGrapes** [FTBTeam/FTB-Academy#131]
I updated the modpack from 1.0.0 to 1.1.0 and my worlds didn't auto transfer and I did not know if they could. I tried to transfer my world to the modpack manually, and when I try play my world, it says "Minecraft ran into a problem and crashed. The following mods have been identified as potential causes 
MinetogetherServer, Minetogether".
A link to the page it sends me
https://paste.dimdev.org/ikimuxesex.mccrash
Any help please?

**Comment by Sunekaer** [comment]
Seem that the file has been corrupted or overwritten with a blank file.
I would recommend you restore the Minecraft\Instances\FTB Academy\config\minetogether.cfg from the link below to fix the issue.

https://s1.sunekaer.com/files/minetogether.cfg

**Comment by SupaSourGrapes** [comment]
Its the same code, will my world work if i just delete the minetogether config? Or is my world corrupted

**Comment by Lombi-chan** [comment]
I think it's because of dynamic trees.
Started a new server today and with the newest update the trees are vanilla.

**Comment by Sunekaer** [comment]
Minetogether does nothing to your world, that crash is normally due to that something is wrong with the cfg file

**Comment by SupaSourGrapes** [comment]
I use the twitch launcher and tried to disable dynamic trees, it wouldnt even let me go to the main menu, i then disabled Dynamic Trees - Traverse Compat, didnt work either. the cfg file for minetogether is the same thing from the link you gave me. Im not sure if my world is able to be saved.

**Comment by aaronhowser1** [comment]
@Lombi-chan This is unrelated, read the changelog
