### ISSUE TITLE
The smeltery doesn't work

### ISSUE THREAD

**Issue by Mokua98** [FTBTeam/FTB-Academy#132]
I've tried building the smeltery both in survival and creative mode and still it doesn't work. I've tried filling it with cobblestone and break them down but nothing has changed. 
The controller works, whatever ore i throw in it gets smelted but I can't make it go into the cast.

**Comment by aaronhowser1** [comment]
You're probably doing something wrong. So the Smeltery is melting ores into molten ores, which is good, but it can't be poured into a cast? Can you post a screenshot of it? Do molten ores reach the level that the Drain is on? It might be built wrong if not.

The Drain has a Faucet on it with a Casting Table the block underneath it, and the Casting Table has a Cast in it right?

**Comment by Mokua98** [comment]
![2019-09-25_22 38 24](https://user-images.githubusercontent.com/55811726/65637947-67978980-dfe5-11e9-8277-1be62e22aa5f.png)

![2019-09-25_22 34 47](https://user-images.githubusercontent.com/55811726/65637827-15eeff00-dfe5-11e9-8245-44cc463e0288.png)

**Comment by aaronhowser1** [comment]
That isn't a cast. You need to pour 2 ingots of Gold or Aluminum Brass on the tool part to make a cast.
