### ISSUE TITLE
Chisel's marble and limestone don't respect cave generation.

### ISSUE THREAD

**Issue by Dakedres** [FTBTeam/FTB-Academy#134]
* **Modpack Version**: 1.0.0

* **Issue**: On Quark's Realistic World Type, Chisel's marble and limestone don't respect cave generation.

* **Image**: ![image](https://user-images.githubusercontent.com/36781227/65722561-b4bd3f00-e069-11e9-8a80-515d6d6f2560.png)

* **Known Fix**: I would recommend disabling marble and limestone world gen for both chisel, and setting spawn rates equal to the calculated spawn rate of all marble types combined as it is now, as I find the number is perfect. Please also use AS' marble instead of Quark's, so we don't have to chisel it.

**Comment by Sunekaer** [comment]
The pack is configured for normal world type, and this won't be changed.
