### ISSUE TITLE
Planting Petals blocks progression in school

### ISSUE THREAD

**Issue by Namerian** [FTBTeam/FTB-Academy#139]
* **Modpack Version**: 1.1.0

* **Issue**: Planting petal blocks progression in school

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Botania(?)

* **Known Fix**: Allow picking up planted petals?

**Comment by Namerian** [comment]
I accidentally planted the brown petals during the Botania tutorial and had to restart the school.

**Comment by mandujib** [comment]
Same. Petal can be placed when shift right clicking on petal apothecary.

**Comment by Sunekaer** [comment]
We are working on a fix to block the planting of petals.

**Comment by Fevix** [comment]
Why not just let the player mine petals in the tutorial? Or have some way to reset certain areas?

**Comment by rendragnet** [comment]
Why was this closed? This is most definitely an issue? Just hit this running my daughter through.  Also, just discovered if you accidentally leave the school, you can't seem to get back to complete the rest of the tutorials :(

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/73118582-a0a42400-3f1b-11ea-9bad-1df7a0d2476b.png)
I can't place these in the current version.

Also, it's intended that you can't return to the school after completing it. Well, more like it's a technical limitation. It would be too difficult to program storing your inventory, xp, and Astral Sorcery research, clearing them, and then giving them back after leaving.

**Comment by rendragnet** [comment]
Got back into the school (set ftba_in_school gamestage, and then /reset_school), just had to run through all the tutes up to b_petal.  /reset_school also sorted it for my daughter.

**Comment by Seff27** [comment]
I’m also having this issue, and my first instinct was also to just /give but it hasn’t shown me how to see a block’s subid with JEI yet. Any chance you could tell me how to do that?

Might just have to reset the school, though it seems like a bit of a hassle. On the bright side, I suppose repetition helps with learning.

And they can definitely be placed in the current version @aaronhowser1, I downloaded it from CurseForge no less than 1 hour ago and this happened to me. Unless the current version just isn’t on CurseForge for... some reason? It says 1.1.1. If it isn’t, where do I get the current version? 

Sorry if there’s something obvious I’m missing, I’m new to the modded Minecraft scene, which is, well, why I downloaded this modpack in the first place.

**Comment by Seff27** [comment]
Sorry about my earlier unpleasantness, turns out I just got the modpack from the wrong launcher. _sigh_

Though now that I’m on the right one (version 1.4.0) it’s not spawning me in the Academy, I’ll have to make a proper report about that later.
