### ISSUE TITLE
Instrumental Mobs and Trumpet Skeletons audio seems out of place in a tutorial modpack

### ISSUE THREAD

**Issue by Spirox128** [FTBTeam/FTB-Academy#141]
* **Modpack Version**: 1.0.0

* **Issue**: The mobs from these mods, while funny, have **extremely** annoying sound effects. The main culprit is the trumpet skeleton who has etched out a small portion of my amygdala and wired it specifically to react violently to his incredibly loud toot. 

I understand that these mobs were included for comical effect, and a way to show how there are some really goofy mods out there for people who want it, but it really, really becomes old after I've been playing this (incredible) modpack for a few weeks now and whenever I hear it it just completely breaks my flow and leaves me irritated. 

As a side note, but still related, the hunger sound coming from Dynamic Surroundings is also very repetitive and just throws me off during game play. However, this is a something I can disable within the mod, so it's not really a problem anymore, but honestly, it's one of the very few sounds from this mod that I would personally have disabled by default due to it's poor design and intrusiveness.

**Comment by aaronhowser1** [comment]
We can see about disabling the hunger sound, or at least turning it way down.

I can see where you're coming from with the trumpet skeletons though, as they're pretty piercing. Dynamic Surroundings allows us to change the volume of every sound in the modpack, including sounds from other mods. We can try doing that to the trumpets too, but I personally don't want to remove them. Instrumental Mobs shows that mods can be funny, same as Hats.
