### ISSUE TITLE
Crashing after joining server

### ISSUE THREAD

**Issue by Jan304** [FTBTeam/FTB-Academy#144]
A friend of mine, get his MC always crashed as soon as he joins the server.
any ideas.
I am the only one how has finished the tutorial, could that be a problem?

**Comment by aaronhowser1** [comment]
Post the client's crashlog and the server's log when he gets kicked

**Comment by Starqls** [comment]
Hey man i got a similar error i got kicked after i placed a Cored Spawner now i cant join the game need help

**Comment by aaronhowser1** [comment]
@Starqls that's probably not the same issue. Keep your issues to your own posts, not other peoples'.
