### ISSUE TITLE
FTB Academy 1.0.0. Items from the first line of inventory disappeared.

### ISSUE THREAD

**Issue by DantalionGG** [FTBTeam/FTB-Academy#146]
FTB Academy 1.0.0. I just ran and suddenly my things from the first line of the inventory (Lower) were gone. Perhaps I pressed some button while running, as I was distracted. I would like to understand whether it is possible to somehow return the lost things, or at least eliminate this problem in the future.

**Comment by aaronhowser1** [comment]
Update to 1.1.0, first of all. I don't know what would have caused this to happen though. Maybe you pressed Z then a number, which would have swapped your hotbar with that row of your inventory?
