### ISSUE TITLE
No-texture purple/black block appears over player's body after using reservoir.

### ISSUE THREAD

**Issue by Zlytheis** [FTBTeam/FTB-Academy#148]
* **Modpack Version**: Version: 1.0.0

* **Issue**: No-texture purple/black block appears over player's body after using the reservoir. I assigned a hotkey to change use on action, loaded up some lava and put it into the magmatic engines. Then I equipped it into a bauble slot. That's when I noticed the no-texture block appearing on my body; I do not know which action specifically caused it. Holding onto the reservoir makes the texture disappear, but it re-appears after switching to a different item in the hotbar. 

* **Link to Log or Crash File Paste**: Did not crash

* **Is it Repeatable?**: Unknown, I cannot take off the texture.  

* **Mod/s Affected**: Thermal Expansion / Baubles

* **Known Fix**: None

**Comment by Zlytheis** [comment]
Oh I just removed the no-texture block. I shift clicked an entire inventory of stuff onto my empty inventory and it disappeared. 

**Repeatable?**: Yes, upon re-holding the reservoir the no-texture block appears.

**Comment by aaronhowser1** [comment]
Update to 1.1.0
