### ISSUE TITLE
Main menu too large

### ISSUE THREAD

**Issue by iamweirdie** [FTBTeam/FTB-Academy#15]
* **Modpack Version**: the only 1 u released to the public, 1.0

* **Issue**: ![](https://cdn.discordapp.com/attachments/303440391124942858/614315156385693715/unknown.png)
as u can see, the main menu is larger than my screen. i've tried adjusting my screen scale in options and removing mainmenuscale mod, but neither work.

* **Is it Repeatable?**: yes

* **Known Fix**: u can work around it by turning off the custom main menu

**Comment by Sunekaer** [comment]
What is your screen res?

**Comment by iamweirdie** [comment]
It's currently set to 1366x768, but I think I found the issue. I adjusted the scale [win10 defaults my res to 100% scale], but then i changed my screen scale to 1920x1080 [win10 default 150% scale]. At first, nothing seemed to happen. However, after i changed my computer scale to 100%, the size got better.

![2019-08-25_23 24 20](https://user-images.githubusercontent.com/34356883/63669677-83fa9900-c78f-11e9-88b1-81ac2789d609.png)
Here's 1366x768 at 100% scale
![2019-08-25_23 25 25](https://user-images.githubusercontent.com/34356883/63669735-a42a5800-c78f-11e9-8135-b7a230191f63.png)
Here's 1920x1080 at 150% scale
![2019-08-25_23 26 05](https://user-images.githubusercontent.com/34356883/63669763-be643600-c78f-11e9-9f28-345251dbe568.png)
Here's 1920x1080 at 100% scale

I believe the issue lies in the windows scaling vs minecraft scaling. I'll need to conduct more tests...

**Comment by Sunekaer** [comment]
Okay, we work out from at people has a 1920x1080 because thats everyone has now a day, and 100% because that is recommended by windows on 1920x1080 res.
Which looks like this 
![image](https://user-images.githubusercontent.com/18720460/64063323-7613a080-cbf3-11e9-9c10-df671a373ffd.png)
