### ISSUE TITLE
Only 4 mods loaded

### ISSUE THREAD

**Issue by CaptianBoo** [FTBTeam/FTB-Academy#151]
* **Modpack Version**: 1.1.0

* **Issue**: It opens up fine, and very quickly. But the thing is it only says 4 mods loaded and when I opened up a world I spawned in a normal world.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: It only shows "Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge".

* **Known Fix**: N/A

**Comment by aaronhowser1** [comment]
Reinstall the modpack
