### ISSUE TITLE
Crash after placing Stabilized Spawner

### ISSUE THREAD

**Issue by Starqls** [FTBTeam/FTB-Academy#152]
Hey guys my game got Crashed while i was on a LAN Server after placing a Spawner with a Draconium Core down. Now i cant join the Server pls help!

* **Modpack Version**: 1.0.0

* **Issue**: Cant join the LAN Server again after i placed a Cored Spawner

* **Mod/s Affected** : Draconium

thanks

**Comment by aaronhowser1** [comment]
Update to 1.1.0, then try again. If it still crashes, post the crashlog.
