### ISSUE TITLE
New Chinese Translation

### ISSUE THREAD

**Issue by MaribelHearm** [FTBTeam/FTB-Academy#156]
Hello, I am a player from China. I want to ask, I found your language project on Crowdin. Can I translate it in Crowdin?

**Comment by Sunekaer** [comment]
Crowdin is outdated, ill shut it down.

**Comment by aaronhowser1** [comment]
You *can* translate it out of Crowdin though. See the README [here](https://github.com/FTBTeam/FTB-Academy).
