### ISSUE TITLE
dynamic trees dont work with plant harvester

### ISSUE THREAD

**Issue by SentryCommando** [FTBTeam/FTB-Academy#16]
* **Modpack Version**: ftb Acadamy

* **Issue**: tree farm doesnt work

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
There's not really anything we can do about this. The guide mentions that regular trees have to be used, I think. You can try making an issue on the Industrial Foregoing issue tracker though.

**Comment by SentryCommando** [comment]
well atleast Quark is in the pack there trees work.

**Comment by aaronhowser1** [comment]
Those aren't Dynamic Trees trees.

You can craft a DT sapling with a Bucket of Dirt to make it into a regular sapling, though.
