### ISSUE TITLE
Issue With Server

### ISSUE THREAD

**Issue by mja00** [FTBTeam/FTB-Academy#161]
* **Modpack Version**: 1.1.0

* **Issue**: It's a strange bug that only happened to 1 player on the server. The player was already in the overworld because they skipped the school and wanted to get into the thick of it. Soon another player joined and started going through the school. At one point the player in the overworld got a message saying "there's less quests for these items so use NEI" or something like that and then their inventory was wiped and replaced with a copy of the quest book. Since this has happened I've just told every player to skip the school so it can't possibly happen again.

* **Link to Log or Crash File Paste**: No log

* **Is it Repeatable?**: No clue

* **Mod/s Affected**: I'm guessing FTB Academy

* **Known Fix**: None

**Comment by Sunekaer** [comment]
do you have any logs of this happening?
