### ISSUE TITLE
Server Issues 

### ISSUE THREAD

**Issue by Boss1318** [FTBTeam/FTB-Academy#162]
Alright so I tried to make a server for me and my friend. We got everything set up but when I attempted to join it said "FTB Academy Mod: Requires version 1.0.3.41 but client has 1.0.3.59.".It said that for several mods. I installed the server file and the whole thing. Any help would be amazing.

**Comment by Sunekaer** [comment]
What version of the pack, are you using the right version of server files?

**Comment by Boss1318** [comment]
Well i'm using twitch to play FTB Academy but the server files were i believe 1.0.0

**Comment by aaronhowser1** [comment]
There's your problem. The server and client have to be the same version.

**Comment by Boss1318** [comment]
I got it to work. Thanks for the help:)
