### ISSUE TITLE
Crashing Issue

### ISSUE THREAD

**Issue by Nab031** [FTBTeam/FTB-Academy#164]
* **Modpack Version**: 1.10.0

* **Issue**: I used my first created world that was made on 1.10.0, I get on later and it says that the two minetogether mods are causing issues

* **Link to Log or Crash File Paste**:  https://paste.dimdev.org/ajizeyezoc.mccrash 

* **Is it Repeatable?**: Happens every time I open my first created world

* **Mod/s Affected**: MineTogether 1.10.2 MineTogetherServer 1.10.2

**Comment by EmotiveEwe85** [comment]
same
