### ISSUE TITLE
"How to install" link broken

### ISSUE THREAD

**Issue by ThisFlynn** [FTBTeam/FTB-Academy#168]
* **Modpack Version**: 1.1.0

* **Issue**: How to install link broken on CurseForge page (https://www.feed-the-beast.com/projects/ftb-academy)

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: n/a

* **Known Fix**: n/a

**Comment by aaronhowser1** [comment]
https://www.curseforge.com/minecraft/modpacks/ftb-academy/files

Click Install

**Comment by ThisFlynn** [comment]
Thanks, but I was reporting an issue not asking for help to install.

Thank issue still exists.
The link is bad.

**Comment by aaronhowser1** [comment]
What do you mean the link is bad? I can see it when logged out
![image](https://user-images.githubusercontent.com/15698722/66402463-8107e080-e9aa-11e9-935e-7d8b8a9a7356.png)
You can also install it through Twitch, as far as I'm aware. If *that* also doesn't work, try installing through the legacy launcher, which you can click by clicking the Linux download button [here](https://www.feed-the-beast.com/).

**Comment by aaronhowser1** [comment]
Oh wait, now I understand

**Comment by ThisFlynn** [comment]
Yeah, that's the one.
I figure it's a good idea for it to work if it's on the page directly linked to from the FTB homepage

**Comment by aaronhowser1** [comment]
I suggest reading [this](https://www.reddit.com/r/feedthebeast/comments/df2b0l/on_the_31st_october_2019_the_partnership_between/), which will explain why that link is broken.

**Comment by ThisFlynn** [comment]
That does seem like it could be related (though a bit early on that timeline)
So.... that's a muuuch larger issue. 

Guess we'll see what happens at the end of the month.
Grabbed the Launcher from that link - so at least I'll be prepared.
Thanks for the help @aaronhowser1
