### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by alxtz1989** [FTBTeam/FTB-Academy#169]
My pc had crash and when i load the world i spawn in the school and can't exit. and when i wrote the command "quit_school" i spawn in the overworld but all my inventory gone.

it happend to me few times and i start 5 times new world

**Comment by aaronhowser1** [comment]
Put the crashlog here

**Comment by alxtz1989** [comment]
i play minecraft and sudenly my pc turn off and it make that the game don't close and save properly the world and when i try to load the world it delete all my inventory and i spawn in the school. at the last time it happen the quests in the book don't restart but when i used the command quit_school all my inventory was deleted.

it's not a a crush of the game itself, but when my pc crush

**Comment by alxtz1989** [comment]
is there any way not lose all inventory when i respawn in the school and quit to the overworld?

sorry for my english, wasn't good at it in school. And thanks for the quick answer!!!

**Comment by aaronhowser1** [comment]
If the bug happened because your pc turned off, there's nothing we can do, sorry. You shouldn't respawn at the school. Does this happen when you die too, or just from the crash?

**Comment by alxtz1989** [comment]
i think just from the crash. 
all the times after the pc crash i respwan at the school. after the first time i make a new world. but even with the command quit_school and gamerule keepinventory true i lost my items in the inventory
