### ISSUE TITLE
Crashes during mod loading/launching at Smooth Font

### ISSUE THREAD

**Issue by ntr09** [FTBTeam/FTB-Academy#170]
* **Modpack Version**: 1.1.0

* **Issue**: Crashes during launch, appears to be related to Smooth Font

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6ba3ecce

* **Is it Repeatable?**: Crashes every time, will not complete mod loading/launching. 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Rogue238** [comment]
I'm having this same issue.
