### ISSUE TITLE
Quest text too small

### ISSUE THREAD

**Issue by SSmale** [FTBTeam/FTB-Academy#171]
* **Modpack Version**: 1.1.0

* **Issue**: the text for the pinned quest is rendering in very small font compared to the other elements and I can't find a setting to adjust it. 

![image](https://user-images.githubusercontent.com/17761689/66586406-743ce580-eb80-11e9-818f-21d5314f6885.png)

**Comment by Sunekaer** [comment]
its do to your scaling, if that doesnt fix it, youll need to report the issue at https://github.com/FTBTeam/FTB-Quests

**Comment by aaronhowser1** [comment]
To clarify, larger GUI scale = larger pinned quests.
