### ISSUE TITLE
Installing the pack issues

### ISSUE THREAD

**Issue by MissKretto** [FTBTeam/FTB-Academy#172]
Hi, I would reallllly like to play this mod but i can't get it going. I've tried to follow the tutorials but nothing...

so i'll start with what i've done so far and then what issue i encountered.

I firstly deleted and uninstalled twitch and reinstalled it with the MC plugin Twitch setup file from FTB's website. I logged in, I followed the instructions on the youtube tutorial with regards to changing my settings. Then when I clicked MODS in the top of the twitch desktop app, nothing loads... It just says 'could not load plug ins' and has a button saying 'Retry'. I keep retrying, but nothing is loading. Have I done something wrong in the set up? I don't see how when it's one of the first steps but I don't know :( 

Is there a way to install the pack manually?

Any help would be much appreciated. Thank you

**Comment by ChooseyArc515** [comment]
for some reason i can't download the modpack all it says is This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 244651 ??

**Comment by aaronhowser1** [comment]
Sorry, I didn't see this issue before just now.

Unfortunately, this looks like it's just Twitch being Twitch. You can try installing the pack through the legacy launcher.

From googling "curseforge 244651", that says that's [TESLA](https://www.curseforge.com/minecraft/mc-mods/tesla/files), which isn't in the modpack. You're trying to download Academy 1.1.0, right?

**Comment by Raenebowe** [comment]
I had this problem. I solved it by going to the website (CurseForge), going to files, choosing the most recent one and clicking download. I told it to use Twitch to download it, and it did. Then I clicked play and it worked just fine.
