### ISSUE TITLE
KubeJS error on server

### ISSUE THREAD

**Issue by Calibanda** [FTBTeam/FTB-Academy#173]
When I go to the console and logs of a server with FTB-Academy (version 1.1.0) I see this error every second:

> [Server thread/ERROR] [KubeJS]: Error occurred while firing 'player.tick' event in kubejs/school.js: <eval>:6 ReferenceError: "ftbacademy" is not defined

Some times (depending on the actions of the players), the error is a little bit different:

> [Server thread/ERROR] [KubeJS]: Error occurred while firing 'block.right_click' event in kubejs/adventure_mode.js: <eval>:6 ReferenceError: "ftbacademy" is not defined

For the moment, I didn't have noticed any issues in-game, but maybe this error could cause some. I tried to see in the js files those functions but (I don't really know JS btw) I didn't find them. 

* **Modpack Version**: 1.1.0

* **Issue**: There are no in-game issues, only errors in the server console

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/37beccfb and
[2019-10-10-1.log](https://github.com/FTBTeam/FTB-Academy/files/3714103/2019-10-10-1.log)

* **Is it Repeatable?**: Every second on server

* **Mod/s Affected**: KubeJS

* **Known Fix**:

**Comment by LatvianModder** [comment]
Are you sure you updated the modpack correctly? It looks like you either have only updated kubejs folder or you havent updated kubejs folder at all

**Comment by Calibanda** [comment]
I didn't update anything. I just install the server with the files of the 1.1.0 modpack. But I could try to reinstall the kubejs folder
