### ISSUE TITLE
Upgrading the iron chest before it tells you to do so softlocks

### ISSUE THREAD

**Issue by quat1024** [FTBTeam/FTB-Academy#175]
* **Modpack Version**: 1.1.0

* **Issue**: In the school:
  * go into the first area with the "general storage"
  * upgrade the iron chest right away before opening all the chests, because you're so excited to see what this item does
  * After opening all the chests the game will tell you to take the chest upgrade out of the wooden chest, but you can't do it.
  * Oops you're stuck
  * You can reset the map to fix it, and tbh it's not that bad because it's literally the first thing you do...

![image](https://user-images.githubusercontent.com/2068021/66635061-687f0c80-ebdc-11e9-94be-15d03c0a105a.png)

* **Is it Repeatable?**: Yes, after resetting the map (which is hard to do btw, because the popup tutorial text obscures the reset button)

**Comment by aaronhowser1** [comment]
The overlay is lower than the buttons in future versions, don't worry

**Comment by aaronhowser1** [comment]
Finally fixed a million years later

**Comment by quat1024** [comment]
Poggers
