### ISSUE TITLE
Storing Energy Quest - Configure energy cell to output energy to the right side

### ISSUE THREAD

**Issue by ArbitraryHubris** [FTBTeam/FTB-Academy#18]
* **Modpack Version**: 1.0.0

* **Issue**: You're instructed to sneak-right-click an energy conduit and replace it with an energy cell - the cell is configured to output to the bottom and needs to be configured to output to the right - the power doesn't move to the furnace.  Not a big deal because there's enough energy to smelt the required items - it's probably just confusing to a learning player that power doesn't fill the furnace.

* **Is it Repeatable?**: Yes

* **Recommended Fix**: preconfigure the energy cell sides to avoid the complication of explaining side configuration at this early stage.

**Comment by aaronhowser1** [comment]
That quest is also supposed to teach about input and output side configuration. The banner says to read the quest to see how to do that.
