### ISSUE TITLE
Dynamic Trees isn't working at all

### ISSUE THREAD

**Issue by sTiKyt** [FTBTeam/FTB-Academy#183]
* **Modpack Version**: 1.1.0

* **Issue**: Trees aren't dynamic

* **Is it Repeatable?**: Yes, everytime when i start new game i have this problem.

![image](https://user-images.githubusercontent.com/35602029/67053862-53a9f800-f14b-11e9-9440-fc0497f09e5f.png)
![image](https://user-images.githubusercontent.com/35602029/67053879-64f30480-f14b-11e9-90fd-0088f01a51d5.png)
![image](https://user-images.githubusercontent.com/35602029/67053908-8522c380-f14b-11e9-9bc8-8d6134e150e0.png)
![image](https://user-images.githubusercontent.com/35602029/67053917-8bb13b00-f14b-11e9-9bfd-44cd327b86d9.png)
![image](https://user-images.githubusercontent.com/35602029/67053946-9ff53800-f14b-11e9-945a-b6a0e3f00833.png)
![image](https://user-images.githubusercontent.com/35602029/67053958-ac799080-f14b-11e9-8524-0951679fcb41.png)
![image](https://user-images.githubusercontent.com/35602029/67053990-c3b87e00-f14b-11e9-9bb4-91dd6640a80a.png)

**Comment by sTiKyt** [comment]
Just figured it out :D
Seems like it was disabled in Config
Had to open `yourMinecraftLocation/config/dynamictrees.cfg`

And set `B:worldGen=false` to `B:worldGen=true`

**Comment by aaronhowser1** [comment]
Yep, this is on purpose. We had it in enabled in 1.0.0, but decided to remove it. In the hopes of not breaking saves, we just disabled it for 1.1.0, and we'll remove the mod entirely in 1.2.0.
