### ISSUE TITLE
Storage room: Stuck trying to get Iron Block 

### ISSUE THREAD

**Issue by jcrites** [FTBTeam/FTB-Academy#184]
I've gotten stuck on my second attempt through FTB Academy. I'm on the step that says:

> Right click the Iron Nugget in the bottom right slot of the Compacting Drawer, then punch the top slot to take out an Iron Block

I was able to extract the Iron Nuggets successfully. However, I am not able to acquire the Iron Block. The Compacting Drawer says the quantity of Iron Blocks is zero. Punching the drawer has no effect and does not provide an item.

![image](https://user-images.githubusercontent.com/88504/67137643-8f959980-f1ed-11e9-8cf0-902531c44707.png)

I'm not sure if I'm doing something wrong or the mod is stuck.

**Comment by jcrites** [comment]
I also checked and the Iron Block item quantity is zero as soon as I enter the storage room for the first time, before getting to that quest.

![image](https://user-images.githubusercontent.com/88504/67137701-4560e800-f1ee-11e9-9d32-e871e2a20d41.png)

**Comment by aaronhowser1** [comment]
You aren't supposed to take Iron Nuggets out. Read the text again, **right** click the Iron Nugget, putting it **in** the Drawer. That makes it so you have 81 nuggets, which is 9 ingots, which is 1 block, so you can take the block out.
