### ISSUE TITLE
Augmented Sextant quest issue

### ISSUE THREAD

**Issue by Fevix** [FTBTeam/FTB-Academy#189]
* **Modpack Version**: 1.1.0
* **Issue**: When crafting the Augmented Sextant, Astral Sorcery copies over the 'waypointed' state. FTB Quests is looking for a 'clean' Augmented Sextant, and there's no way (that I've found) to clear this waypointed state to get the Quest to recognize the Sextant.

1. Craft a Sextant
2. Right click with the sextant at night, find a star, and place a marker(Small Shrine, Desert Shrine, Ancient Shrine) over it. The Sextant now has a line in the tooltip with that marker name, and NBT data. (This is what I call the 'waypointed' state)
3. Use this Sextant to craft an Augmented Sextant. Note that the newly crafted Augmented Sextant retained the Sextant's waypointed state. Because of this waypointed state, the quest does not accept the Augmented Sextant for the quest. 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Astral Sorcery, FTB Quests

**Comment by aaronhowser1** [comment]
The item in the quest is set to trigger when a Sextant that contains the NBT `{astralsorcery:{advanced:1b}}`. This'll require some hacky kubejs script to fix, but it will be done
