### ISSUE TITLE
Easter Egg Crash

### ISSUE THREAD

**Issue by C3l4h1r** [FTBTeam/FTB-Academy#19]
* **Modpack Version**: 1.0.0

* **Issue**: Interacting with the Easter egg in the starter area crashes my connection (disconnect from server)

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes, right click easter egg in starting area

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by aaronhowser1** [comment]
Really? That's very strange. It's supposed to just give you 5 levels of experience. Can you try to reproduce this and send the log?

**Comment by C3l4h1r** [comment]
[debug.log](https://github.com/FTBTeam/FTB-Academy/files/3545770/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Academy/files/3545771/latest.log)
I couldn't recreate the issue on a single player save, here's the logs for a clean server setup (haven't touched anything but the eula.txt) If you do a search for "[net.minecraft.server.dedicated.DedicatedServer]: <Celahre> picking up egg" that's right before I pick up the egg

It doesn't make a difference if the player is opped or not.

On reconnect you will have still received the experience though. :)
