### ISSUE TITLE
Astral Sorcery Attuned Wand Quest not Completing.

### ISSUE THREAD

**Issue by Daishan2078** [FTBTeam/FTB-Academy#192]
FTB Academy
MC Version: 1.12.2
Pack Version: 1.1.0

The Attuned Wand quest is not completing once you make wand. 

I've made 2 different wands and both fail to complete quest.

This is the only quest in the modpack I've not completed and FTB Quest leaderboard is at 83%, was hoping that there were hidden quests once finished all of them. As this quest ins't able to complete i'm stuck.

**Comment by 13579resu** [comment]
I've had the exact same issue! It didn't work on the Discidia attuned one (the first red one), but it worked for me when I crafted the Aevitas attuned one (the green one).

**Comment by Daishan2078** [comment]
Thanks for the info, I'll give that a try. 👍

**Comment by aaronhowser1** [comment]
Even if Aevitas works, please keep the issue open so I remember to actually fix it

**Comment by Daishan2078** [comment]
Roger.

**Comment by Spongman** [comment]
same. vicio doesn't submit.
