### ISSUE TITLE
Quest Progression stuck on 84%

### ISSUE THREAD

**Issue by 13579resu** [FTBTeam/FTB-Academy#193]
* **Modpack Version**: 1.1.0

* **Issue**: As the title says, I'm currently facing the issue where my quest progress as measured by the leaderboards is stuck on 84%:
[https://i.redd.it/pwl751yl4yu31.png](https://i.redd.it/pwl751yl4yu31.png)
I have already completed every quest line as shown here:
[https://i.redd.it/u9h68bjv4yu31.png](https://i.redd.it/u9h68bjv4yu31.png)
[https://i.redd.it/uygeloiv4yu31.png](https://i.redd.it/uygeloiv4yu31.png)
[https://i.redd.it/8zxnygiv4yu31.png](https://i.redd.it/8zxnygiv4yu31.png)
I would like to know if I have done something wrong or the leaderboards calculated a wrong amount or some leftover quests are still hidden.

* **Is it Repeatable?**: Yes, my friend and other people as well noticed the exact same issue

* **Possible Reason**: I have counted the amount of completable quests which is 304. Also I have reverse engineered the chapters folder of the FTBQuests config so it looks like this now:
[https://i.redd.it/97n2aob6izu31.png](https://i.redd.it/97n2aob6izu31.png)
Each folder contains a file named "chapter.nbt" and some other nbt files which represent the associated quests.
Those backend quests seem to be set to invisible when viewed through an nbt editor, which contain 35 quests.
If you count the amount of nbt files from these folders that are not "chapter.nbt" you get 339 quests.
If you calculate 304/339 you get 0.8968, so that cannot be what's shown as the quest progress.
If you count all the files in those folders you get 358 files, calculate 304/358 and you get 0.8492 which is much closer to what is shown as quest progress, so the algorithm for calculating quest progress clearly does not take into account that some files aren't actually quests.

* **Possible Solution**: An easy fix for that from a programming perspective would be to include a line that skips each file named "chapter.nbt" while calculating the amount of total quests. Also, the algorithm would need to exclude those backend folders.

**Comment by aaronhowser1** [comment]
Instead of reverse-engineering the nbt files, use the command `/ftbquests editing_mode`. That will allow you to see quests that are locked and invisible, and you can see if any of those aren't completed. If the ones that are stopping 100% quest completion are the invisible ones in the backend chapter, then that's a problem.

**Comment by 13579resu** [comment]
As this was a public server i took the pictures on and i did not have the permissions to type in that command, I had to do the quests manually on a singleplayer world again; this time I used JEI cheat mode to accelerate quest progression.
I am still stuck on 84% however:
https://imgur.com/a/S0s63KP

**Comment by aaronhowser1** [comment]
If you force complete the backend quests, does it increase your quest progress?

**Comment by 13579resu** [comment]
They are already completed as shown in the imgur album. Do you want me to type in some sort of command by any chance?

**Comment by aaronhowser1** [comment]
Oh sorry, didn't see that. I'll ping @LatvianModder, the quest mod dev.

**Comment by Daishan2078** [comment]
I have this same issue. It seems its bacause I skipped the school quests. it gave me the stated quests as complete, but it did not complete the "Go to the storage room.." etc.

**Comment by 13579resu** [comment]
I thought so at first too, but nope, it still gives you only 84% if you've done absolutely everything

**Comment by Daishan2078** [comment]
Click the auto pin button on the quest log, it chose the uncompleted ones

**Comment by Daishan2078** [comment]
![2019-10-27_04 56 12](https://user-images.githubusercontent.com/57045998/67632156-47721900-f876-11e9-97ef-8f31d7b385ae.png)

**Comment by 13579resu** [comment]
Even then, there's just nothing showing up:
https://imgur.com/a/q0bC7hP

**Comment by Daishan2078** [comment]
Hmm, thats weird, I know why I'm stuck because I can see the uncompleted background 'quests' Not sure why there not showing up for you. Sorry I couldn't help :(

**Comment by 13579resu** [comment]
It's the same on the public server, so at least i know now that i haven't messed up the quests there:
https://imgur.com/a/cg3EWiw

**Comment by LatvianModder** [comment]
The progress calculation is most likely off. My guess is it's something to do with subchapters because thats the only *super weird* part of the code lol. I will take a look at it

**Comment by 13579resu** [comment]
The issue got fixed in the newest version of FTBQuests:
https://i.imgur.com/cmvHbz8.png
All you have to do now is to include FTBLib and FTBQuests on the newest version in the modpack.
