### ISSUE TITLE
Insane Graphical Bug

### ISSUE THREAD

**Issue by MadDog443** [FTBTeam/FTB-Academy#195]
Version: 1.1.0
Every time my character walks it bugs out and the game crashes sometimes too. I will link a few logs and a video too. I was using Talyor's Algorithm and had all the BetterFPS settings on.
I believe that the issue has to do with BetterFPS and it's Algorithms.
Here are some logs and a video showing the glitch: https://drive.google.com/drive/folders/1EEtpGOwZjBi8lFZw2eRmYK6K4qmjba28?usp=sharing

**Comment by aaronhowser1** [comment]
Yeah, just try changing the algorithm to something else. If that doesn't work we can reopen the issue.
