### ISSUE TITLE
KubeJS issues on older versions of Java

### ISSUE THREAD

**Issue by lukov4** [FTBTeam/FTB-Academy#196]
* **Modpack Version**: 1.1.0

* **Issue**: after completing opening all chest and then remove the wood to iron upgrade from the chest. I applied it to the chest as instructed however the quest did not progress.

* **Is it Repeatable?**: yes, even after resetting the school it continues

**Comment by WyattLuke** [comment]
Can also confirm this is an issue.
Pack version 1.1.0
Also tried running the pack in a server for errors. After opening the chests The server log started repeating
"[22:45:44] [Server thread/ERROR] [KubeJS]: Error occurred while firing 'player.tick' event in kubejs/school.js: <eval>:6 ReferenceError: "ftbacademy" is not defined"
This error stops when I exit the server and starts again after rejoining. It also continues even after restarting the server.

And just to clarify I did try this on both single player and multiplayer worlds(not that it should matter).

**Comment by aaronhowser1** [comment]
@lukov4 please update Java and try again
