### ISSUE TITLE
No recipe to make Purple slime block from liquid purple slime

### ISSUE THREAD

**Issue by fatsack** [FTBTeam/FTB-Academy#198]
* **Modpack Version**: 1.1.0

* **Issue**:  No recipes for liquid purple slime except for knightslime alloy.  So if you melt too much you have to waste buckets, or find somewhere to dump it, or leave it in your TC smeltery.  should have recipe to pour a block from the smeltery or some other use.

* **Mod/s Affected**: Tinkers Construct, Craft Tweaker

* **Known Fix**: add a recipe?

**Comment by enescaglayan** [comment]
You can just kill the slime in the bucket and make the block with it.

Issue fixed!

**Comment by fatsack** [comment]
What do you mean by "kill the slime in the bucket"?

**Comment by aaronhowser1** [comment]
Pour the liquid slime on the ground and wait, and it'll eventually spawn a
Pink Slime mob. Kill that for the items.

**Comment by enescaglayan** [comment]
Oh also if you dont know how to get it (i also dont know so i researched yt) you need make a mob slaughter factory. Also you will get managed to get liquid slime but when you use bucket on the factory, it will fill the bucket with liquid meat. So you need do a quest that gives you a portable fluid tank, make fluiduct then place them bottom of the machine.

Then, go machine click square with brown color untick all things, and place servo make it ignore redstone BOOM you are ready.

sorry for my really really bad spelling anyways i hope its understandable.

**Comment by aaronhowser1** [comment]
Wait, PURPLE slime, not PINK. Yeah, ignore us lol

**Comment by aaronhowser1** [comment]
Non-issue, there isn't supposed to be a recipe (I think. If there is a recipe for blue slime fluid to blue slime block, let me know)
