### ISSUE TITLE
Client Crashed entering Nether.

### ISSUE THREAD

**Issue by T012m3n7oR** [FTBTeam/FTB-Academy#199]
* **Modpack Version**:  FTB Academy 1.1.0 (Most up to date from the FTB launcher as of the time of this posting)

* **Issue**: Client Crashed entering the Nether

* **Link to Log or Crash File Paste**:
Crash Log 1: https://paste.feed-the-beast.com/view/79e43625
Crash Log 2: https://paste.feed-the-beast.com/view/539a6923
Crash Log 3: https://paste.feed-the-beast.com/view/87c19c8d
Crash Log 4: https://paste.feed-the-beast.com/view/c1d7b512
Crash Log 5: https://paste.feed-the-beast.com/view/13062776
Crash Log 6: https://paste.feed-the-beast.com/view/9261b765
Crash Log 7: https://paste.feed-the-beast.com/view/af6b70c0
Crash Log 8: https://paste.feed-the-beast.com/view/4b9bd3d9
Crash Log 9: https://paste.feed-the-beast.com/view/ae37ff2c
Crash Log 10: https://paste.feed-the-beast.com/view/526ce2bc
The last four lines of the debug log don't appear to be of any use:
[01:18:20] [Client thread/WARN] [net.minecraft.client.network.NetHandlerPlayClient]: Received passengers for unknown entity
[01:25:31] [Client thread/INFO] [dsurround]: Creating Nether SeasonInfo for dimension the_nether
[01:25:31] [Client thread/INFO] [dsurround]: Setting weather renderer for dimension [the_nether]
[01:25:31] [Client thread/INFO] [journeymap]: Mapping halted in C:\FTB Launcher\FTBAcademy\minecraft\journeymap\data\mp\My~Server~Local~\DIM0

* **Is it Repeatable?**: No, can enter the Nether now.  ~Extremely slow though, I did create a mob farm before leaving it previously with a draconic spawner.  It is possible it is spawning faster than I'm killing them.~ Nether is slow due to the sheer amount of mobs.  Back to the drawing board.

**Comment by aaronhowser1** [comment]
> Nether is slow due to the sheer amount of mobs. Back to the drawing board.

Sorry for the extremely late reply. Does turning the server to peaceful then loading the Nether fix it? Or otherwise just removing the mobs in general? I'll close this for now, but I'll reopen if that didn't work.
