### ISSUE TITLE
[Suggestion] Just Enough Throwing In Fluids

### ISSUE THREAD

**Issue by Lykrast** [FTBTeam/FTB-Academy#2]
[Just Enough Throwing In Fluids](https://www.curseforge.com/minecraft/mc-mods/jetif) adds JEI support for throwing items in fluids. In this modpack this would give a JEI recipe to:

* Crystallized/Empowered Oil from Actually Additions
* ~~Astral~~ Infused Wood from Astral Sorcery

And I feel like this would help just a bit, which for something aimed at begineers is nice to have.

**Comment by ZephyrWindSpirit** [comment]
Astral wood is called infused wood and vibrant infused wood.
