### ISSUE TITLE
MultiMC Forge won't install automatically

### ISSUE THREAD

**Issue by DemonInTheCloset** [FTBTeam/FTB-Academy#20]
* **Modpack Version**: FTB Academy 1.0.0

* **Issue**: Installing the Modpack through MiltiMC's Twitch URL option didn't install forge, it had to be manually added

* **Is it Repeatable?**: Yes:
1.  Select add instance in MultiMC 5
2. Select Twitch URL option
3. Copy and paste this URL into the field: https://www.curseforge.com/minecraft/modpacks/ftb-academy/download/2766338?client=y
4. Select add Instance, all mods but Forge will install

* **Mod/s Affected**: Forge, everything else was there

* **Known Fix**: Add Forge Manually
1. Select the instance
2. On the menu click edit instance
3. Select Version
4. Select Install Forge
5. **Install the version 14.23.5.28.38** (the current Latest version not the recommended one), the game won't launch if you select a newer version.

**Comment by Sunekaer** [comment]
#13
