### ISSUE TITLE
Unable to access (Store items in or view) Refined Storage drives

### ISSUE THREAD

**Issue by KickAK47** [FTBTeam/FTB-Academy#200]
Modpack Version: **1.1.1**

 Issue: When I try to store items in the Refined Storage system I can't put items in it. It is all set up correctly but it doesn't work.

 Is it Repeatable?: **Yes**. I've restarted the game multiple times and it doesn't work.

 Mod/s Affected: **Refined Storage**

 Known Fix: **None**.

**Comment by aaronhowser1** [comment]
You likely don't actually have it set up correctly. Make sure that power is being provided to the Controller, make sure that the Disk Drive is connected to the Controller, make sure Disks are in the Disk Drive and that they have space in them, and make sure that the Grid is also connected to the same Controller. Post screenshots of your setup.
