### ISSUE TITLE
api.creeper.host

### ISSUE THREAD

**Issue by LaoziTool** [FTBTeam/FTB-Academy#203]
* **Modpack Version**: 1.1.1

* **Issue**: why does the pack keep going out to api.creeper.host?

* **Link to Log or Crash File Paste**: no crash log

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**: Turn off the internet?

**Comment by Sunekaer** [comment]
Because of the MineTogether chat
