### ISSUE TITLE
Laser Item Relay, Hopper Item Interface, Drawer Controller

### ISSUE THREAD

**Issue by fatsack** [FTBTeam/FTB-Academy#206]
* **Modpack Version**: 1.10

* **Issue**: When you have a stack of 3 blocks, top is empty compactor drawer, middle is Item Interface Hopper, bottom is Drawer controller (connected to Compactor drawer via other drawers) and then have an Advanced Item Laser Relay with empty blacklist on the Item Interface Hopper, it will pull from connected storages into the Item Interface Hopper and down into the drawer controller for items that the Drawer Controller cannot store, destroying the items. It only works when the drawer above the item interface hopper is a compactor drawer, and empty, otherwise it outputs the contents of the top drawer.  

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Actually Additions, storage drawers

* **Known Fix**: remove the compactor drawer above the Item Interface Hopper

**Comment by fatsack** [comment]
*Also, the Drawer Controller doesn't send pull requests when Item Interface Hopper is pointing into it with nothing above the Item Interface Hopper

**Comment by aaronhowser1** [comment]
Can you post a screenshot? I'm having trouble picturing this.
