### ISSUE TITLE
Game cannot launch

### ISSUE THREAD

**Issue by Landeloth** [FTBTeam/FTB-Academy#208]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by T012m3n7oR** [comment]
That looks more like a launcher issue then a modpack issue.  Have you tried the FTB Launcher?

**Comment by aaronhowser1** [comment]
Yep, this is a Twitch bug. Basically just keep trying, wait, or use a different Launcher (like the FTB launcher).
