### ISSUE TITLE
My world has no End???

### ISSUE THREAD

**Issue by Gi-Coast** [FTBTeam/FTB-Academy#209]
FTB Academy 1.1.1, Forge 14.23.5.2846

* **Issue**: 
Basically my world made the End dungeon but there was no portal, I made a creative super flat to see, I couldn't also build the portal, it was not activating, even using a command to make it appear, the block appeared but nothing happened when I tried to enter

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes, as I said I tried in a separate world
* **Mod/s Affected**: 

* **Known Fix**: 

-->

**Comment by aaronhowser1** [comment]
Reinstall the pack completely (make a world backup on your desktop or anywhere else). I have no idea what could be causing this to happen.

Maybe make another test world, not superflat. Go into spectator mode and fly around the stronghold, it might just be very hidden.
