### ISSUE TITLE
Modpack can't multiplayer

### ISSUE THREAD

**Issue by Iraduhiim** [FTBTeam/FTB-Academy#212]
I can try play modpack wth my friend and we can't finish the tutorial stage only 1 player go the overworld other player stay the tutorial (yes I know my eng is bad -1 )
And I try the '' /setblock ~ ~ ~ portal '' commads and I go nether by this time my friend setup from overworld to hell and we meet the hell after exit the hell with overworld portal
Finally we meet the overworld but ı can not the anything (exp:open crafting ,breaking block)

**Comment by aaronhowser1** [comment]
You both need to finish the tutorial separately. Don't make a team until you both finish the tutorial. You can do the command `/skip_school` to leave the school and allow yourself to interact with the world.
