### ISSUE TITLE
FTB Academy Issue -  Can't start Minecraft anymore

### ISSUE THREAD

**Issue by RickBeli** [FTBTeam/FTB-Academy#213]
So, i was flying around in the Nether, then Minecraft crashed, and instantly closed.
Now when i try to open my world, it just closes it automatically. Basically, i can't access to that world.

I'm playing FTB Academy, (forge-14.23.5.2838). I have the latest Java update.

Here's the Crash Report:

https://paste.feed-the-beast.com/view/22853592

**Comment by aaronhowser1** [comment]
This is an issue with Instrumental Mobs, but it was fixed in Academy 1.1.0. Update to that version, and make another issue if it doesn't fix it.
