### ISSUE TITLE
Tinkers construct and a vanilla recipe use the same input.

### ISSUE THREAD

**Issue by T012m3n7oR** [FTBTeam/FTB-Academy#215]
**Modpack Version**: 1.1.0

* **Issue**: Tinkers construct/vanilla recipe uses the same input blocks. (Two wooden Slabs. First creates a Item rack, second creates the wooden plank respectively.)

https://ibb.co/0yDZV1Z - Item Rack Recipe
https://ibb.co/R67pYxM - Wooden Plank Recipe
https://ibb.co/nz9GcdL - RS Crafting Grid.

* **Is it Repeatable?**: Yes

* **Known Fix**: Remove one from JEI?  If choosing the Item rack, may want to disable from TConstruct if possible.

**Comment by aaronhowser1** [comment]
That's a Quark recipe, and it's shapeless. That means the two slabs can be anywhere in the crafting menu, not just right next to each other. So these recipes don't actually conflict, one requires them to be right next to each other, and the other does not.
