### ISSUE TITLE
Error on Twitch Mod Section

### ISSUE THREAD

**Issue by OmAn94** [FTBTeam/FTB-Academy#216]
* **FTBAcademy-1.1.1-1.12.2**: 

* **Issue**: Error trying to start Game

* **Link to Log or Crash File Paste**: Error al descargar el archivo, el contenido difiere de lo que se esperaba.
Nombre: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Nombre del archivo en el disco: jna-4.4.0.jar
Ruta: E:\Games\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Existe: File

* **Is it Repeatable?**: Yes, every time, also already re-downloaded after uninstalling the previous one, 

* **Mod/s Affected**: 

* **Known Fix**: 

Images
![imagen](https://user-images.githubusercontent.com/13035104/69176803-b30e7580-0b06-11ea-9b84-130da0ef7232.png)

**Comment by OmAn94** [comment]
Ok already works apparently, just used the java launcher instead of the native one, also, decrease RAM to 6G, and no Java Arguments. If something goes wrong would report it.

**Comment by alexis605** [comment]
Help gives me the same error, how do I fix it?

**Comment by aaronhowser1** [comment]
Use the legacy launcher @alexis605

**Comment by carapucho** [comment]
and what do you do with the legacy launcher?

**Comment by aaronhowser1** [comment]
Play Academy? This is a Twitch bug, so it doesn't happen when not using Twitch.

**Comment by carapucho** [comment]
I'm sorry, i understand what i have to do but don't know how to. If you could give me an explanation I would be very thankful.

**Comment by aaronhowser1** [comment]
Download the Legacy Launcher [here](feed-the-beast.com/), launch it, click on Academy, download it, then play it
