### ISSUE TITLE
Can't make void satchel

### ISSUE THREAD

**Issue by Lincxx** [FTBTeam/FTB-Academy#217]
* **Modpack Version**: 1.12.2

* **Issue**: Can't make the void satchel, I have tried different chiseled blocks, but seems to be working. I'm using the FTB launcher to play this modpack. 

* **Is it Repeatable?**: Not sure

* **Mod/s Affected**: 
![nosatrchel](https://user-images.githubusercontent.com/8806007/69452674-39f26680-0d30-11ea-83bd-f3bb181e10b2.png)

**Comment by aaronhowser1** [comment]
Use vanilla Cobblestone.
![image](https://user-images.githubusercontent.com/15698722/69470280-18f33b00-0d5b-11ea-8951-0c3f01f15ddd.png)
