### ISSUE TITLE
Misleading information in the guide: Mob Swab

### ISSUE THREAD

**Issue by Venom31** [FTBTeam/FTB-Academy#218]
* **Modpack Version**: 1.1.0

* **Issue**: The FTBGuide states, under modpack_guide/technology/machines/resource_gathering/mob_grinding/spawning/, that with Mob Swab (mob_grinding_utils), "you can [...] right click it on a Mob Spawner to change it to spawn that mob. This also works great with Stabilized Mob Spawners." In survival, only right clicking it on a Mob Spawner works. Stabilized Mob Spawners from Draconic Evolution only change their type to mob spawn egg type in Creative. Therefore, new players will get misled and confused, which defeats the purpose of the guide.

* **Link to Log or Crash File Paste**: no crash

* **Is it Repeatable?**: yes

* **Mod/s Affected**: FTBGuide -> Draconic Evolution / mob_grinding_utils

* **Known Fix**: Change the affected text of Mob Swab description to something like "This only works on regular spawners, so if you'd like to use Stabilized Mob Spawners, change the mob type beforehand."

**Comment by aaronhowser1** [comment]
Really? I didn't know it didn't work on Stabilized Mob Spawners in survival.

**Comment by Venom31** [comment]
Yep. Ended up with two useless empty Stabilized Mob Spawners before I realized my mistake. I'm kinda new to Draconic Evolution, so I had to double-check its tablet, and yup!

**Comment by aaronhowser1** [comment]
Ok the Guide mentions that only Souls can change already-stabilized Spawners now.
