### ISSUE TITLE
Power outage causes players to return to school, deleting inventory

### ISSUE THREAD

**Issue by Robball14** [FTBTeam/FTB-Academy#227]
* **Modpack Version**: 1.1.0

* **Issue**: last time i quit the game, i was on a island in the overworld. today, i entered in the world and i was in the academy dimension and when i opened the quest book (has requested by the modpack, because it wouldn't let me using the "skip" button) the game teleported me back in the overworld, it was completely fine, the quests i did were still completed, but my inventory (except for the backpack) and my stats were completely gone

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/e77dd71d

* **Is it Repeatable?**:  i think it's rare for that to happen again

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Did you quit due to a power outage or something similar? This happens for some reason when people quit because of something like that.

**Comment by Robball14** [comment]
Now that you make me think about it, yesterday i had  a blackout. if the problem is the fact my computer suddenly shut down, i guess you can't do anything about it. 
Thank you for the help, at least I know it's not a computer problem
--
Inviato da Libero Mail per Android giovedì, 05 dicembre 2019, 01:34PM +01:00 da Aaron Howser  notifications@github.com :

**Comment by Kyscen** [comment]
Hello,
I had the same problem yesterday : I play with a friend with Aternos, but the server restart, and when we had reconnect in the server, we are in the academia, without inventory but all the success we did before complete. But we arrived to found the place where we live, with all the things we did, but we can't craft items or destroy blocks... Also in creative !!
what we have to do ? I don't achieve to complete the tuto a second time before I found where we live, maybe because the success are already complete ?

**Comment by Robball14** [comment]
Sadly, you have to remake everything. When i returned to the world, the backpack i had in the Bauble inventory was the only thing that didn't get deleted. The rest of the inventory, and stats, was completely gone. So, before making everything again, make the backpack (the one in "Getting started" quest chapter) and take it always with you. when the glitch reappears put all the important things into the backpack and place it in the bauble inventory 
--
Inviato da Libero Mail per Android mercoledì, 15 gennaio 2020, 02:29PM +01:00 da Kyscen  notifications@github.com :

**Comment by Kyscen** [comment]
I found it : we have to write the command /quit_school in chat !!

**Comment by aaronhowser1** [comment]
That deletes all your inventory. I suggest reloading a backup instead.

**Comment by Kyscen** [comment]
If we found the place of living, like me, we can transfer all the stuff in chest and do the command

**Comment by aaronhowser1** [comment]
I mean, don't do the command at all. Load a backup where you aren't in the school where you still have all your stuff.

**Comment by Kyscen** [comment]
too late...
