### ISSUE TITLE
jna-4.4.0.jar when trying to launch?

### ISSUE THREAD

**Issue by PhatNap** [FTBTeam/FTB-Academy#234]
Modpack Version: 1.11, Minecraft is 1.12.2

* **Issue**: whenever I try to run the mod pack it comes up with this error,

"Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: C:\------\------\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File"
Attached Image:
![minecraft error](https://user-images.githubusercontent.com/58716867/70492576-1cf4bc00-1ac2-11ea-874c-f9af281f8e98.JPG)

Whenever I try to boot it up it happens, it also happens with several other modpacks and uninstalling and reinstalling does nothing.

**Comment by Sunekaer** [comment]
Hi Phat,
Sadly nothing we can do about this, please contact twitch as they need to fix this.

**Comment by aaronhowser1** [comment]
You can also try using the FTB Launcher, at feed-the-beast.com
