### ISSUE TITLE
Occasionally you can't mine in some areas of the Nether 

### ISSUE THREAD

**Issue by Barberfluids** [FTBTeam/FTB-Academy#236]
Hi There,

Not sure if this issue is related to chunk loading, I have run into a few times mining in a specific area in the Nether where I try to use a diamond pickaxe on Netherrack and can't mine anything.  I switch picks and go to another area and can mine correctly. 

* **Modpack Version**: 
FTBAcademy-1.1.1-1.12.2.zip
* **Issue**: 
Mining in a specific area in the Nether where I try to use a diamond pickaxe on Netherrack and can't mine anything.  I switch picks and go to another area and can mine correctly. 
* **Link to Log or Crash File Paste**: 
 FTB Launcher logs:

* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 
Not sure what's causing the issue
* **Known Fix**: 
Unknown

**Comment by aaronhowser1** [comment]
You don't need to post the log unless it's a crash.

You're likely mining in someone else's claimed chunks, You can't mine in someone else's claimed chunks.

**Comment by Barberfluids** [comment]
Sorry no, this isn't a server version of FTB.  I am running single player on my laptop.

**Comment by aaronhowser1** [comment]
Very odd then. Can you place blocks in those areas?

**Comment by Barberfluids** [comment]
I have not tried that.  However, I have also seen this issue at spawn point in the Overworld.  I will use a pick axe and then it stops being able to break any blocks.  I have to exit and start up the world to be able to use the pick axe again.  It just happens.
