### ISSUE TITLE
Some quest completions do not occur after crafting, you have to place the item onto the ground and break it and put back into my inventory for the quest to be recognized as complete

### ISSUE THREAD

**Issue by Barberfluids** [FTBTeam/FTB-Academy#237]
Some quest completions do not occur after crafting, you have to place the item onto the ground and break it and put back into my inventory for the quest to be recognized as complete

* **Modpack Version**: 
FTBAcademy-1.1.1-1.12.2.zip
* **Issue**: 
Some quest completions do not occur after crafting, you have to place the item onto the ground and break it and put back into my inventory for the quest to be recognized as complete
* **Link to Log or Crash File Paste**: 
 FTB Launcher logs:

* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 
Affects quest completion
* **Known Fix**: 
Place the item on the ground, break it and put back into your inventory and you will get credit for quest completion.

**Comment by aaronhowser1** [comment]
>  you must provide the version of the pack this issue happened

We need the **modpack** version, not the minecraft version

> please use http://paste.feed-the-beast.com/ to paste the text of your log/crash file 

Do not paste the entire log in the issue.

Quests should trigger when you have the item in your inventory. What quests specifically are having this issue?

**Comment by Barberfluids** [comment]
They do not list an exact version number here: https://www.curseforge.com/minecraft/modpacks/ftb-academy/files/2818179

However the file is called. FTBAcademy-1.1.1-1.12.2.zip

**Comment by Barberfluids** [comment]
This issue happened with a several quests including the Latex Processing Unit

**Comment by aaronhowser1** [comment]
Please use http://paste.feed-the-beast.com/ to paste the text of your log/crash file. Make sure that this includes you trying to complete the quest and it failing (preferably, also say something in chat here to add that to the log so I can control+F it), and then throw it on the ground and pick it back up to complete it.
