### ISSUE TITLE
The ModPack causing Launching Process to fail

### ISSUE THREAD

**Issue by ygyuuffut** [FTBTeam/FTB-Academy#241]
* **Modpack Version**: Academy 1.1.1

* **Issue**: While Launching, ran into the error with the info given below

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/aaa85f66

* **Is it Repeatable?**: This occurs every time the modpack is launched

* **Mod/s Affected**: not any Mods is affected as far as the game launching goes (uncertain)

* **Known Fix**: Manually Download the jna-4.4.0 from minecraft website and replace it to the jna folder

**Comment by Sunekaer** [comment]
Sadly this is a twitch and not something we can fix.
