### ISSUE TITLE
Server world don't spawn in the academy

### ISSUE THREAD

**Issue by Gendi98** [FTBTeam/FTB-Academy#244]
So, i've been playing in Singleplayer for a while, then i convinced my friends to play academy.

I wanted to start a fresh world and let them pass through the academy, so i started the server and let it create a new world... dont spawned in the academy, then i delete that world folder, created a new world in Singleplayer, used /setworldspawn in the academy and uploaded it to the server, started the server and i spawned in the Overworld without the quest book and no quest book option in the inventory, what am i supposed to do?

**Comment by aaronhowser1** [comment]
Reinstall the modpack entirely first. After that, copy the server log to pastebin (or upload the file itself here directly if it's too big).

Don't set the world spawn in the school dimension. When a new player spawns, a new school is generated specifically for them. You can't complete a school that someone else has already done.

Also, make sure that mods in general work on the server. It could be that you're just running vanilla or something, which would explain why FTB Academy Mod doesn't work.

**Comment by Gendi98** [comment]
@aaronhowser1 thanks for ur help, i've already solved the problem.

My host was initializing minecraft as vanilla, i ran the serverstart.bat from the putty and it all worked, thanks for your help!!
