### ISSUE TITLE
Storage Basics not showing completion

### ISSUE THREAD

**Issue by AJGame** [FTBTeam/FTB-Academy#246]
* **Modpack Version**: 1.1.1

* **Issue**: After completing all the quests in Storage Basics it shows 92% completion and not completed. All icons have the green checkmark, all rewards have been claimed. 

* **Link to Log or Crash File Paste**: No crash to report 

* **Is it Repeatable?**: Unknown

* **Mod/s Affected**: Unknown

* **Known Fix**: Unknown

**Comment by aaronhowser1** [comment]
There's a hidden quest in there that relies on the Draconic Evolution quests in Tech Advanced.

**Comment by aaronhowser1** [comment]
Wait no that was changed in 1.1.0. Can you show a screenshot?

**Comment by AJGame** [comment]
Actually, the issue did resolve itself, I think, as I have not completed the last quest. I had an additional quest that popped up to build a large storage crate after I built the Actually Additions Empowerer under Tech Advanced. That was the one that I could not see previously.

**Comment by AJGame** [comment]
I just wanted to give you an update. I made the large storage crate collected the reward and Basic Storage is 100% complete. So there is a hidden quest still in Tech Advanced it's just under AA instead of DE.
