### ISSUE TITLE
Leadstone Conduits do not seem to transfer power

### ISSUE THREAD

**Issue by KINGKNIGHTLY** [FTBTeam/FTB-Academy#247]
* **Modpack Version**: 1.1.0

* **Issue**: When connecting leadstone conduits to a steam dynamo in the academy modpack the leadstone did not transfer power. The set up was as follows: Dynamo->4leadstone conduit-> eletric furnace. All from Thermal Expansion and in other modpacks (DW20) this worked without issue

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal expansion/foundation

* **Known Fix**: none

**Comment by KINGKNIGHTLY** [comment]
Hah I forgot to add coal. FML.

**Comment by aaronhowser1** [comment]
Lol it's no problem. Thermal is weird like that, I actually made a quest specifically for mentioning that Dynamos don't output power unless they have fuel for 1.2.0.
