### ISSUE TITLE
Crash,During the Launch.Evry time.Twitch.FTB Academy.PLS.Help

### ISSUE THREAD

**Issue by Kimodd** [FTBTeam/FTB-Academy#248]
From the first download, evry time I try to  launch the game.it start to load and crash after a few seconds after.I tried to reinstall Java,Twitch and the modpack,but it didn't help.Pls help me.
[crash-2020-01-25_23.23.09-client.txt](https://github.com/FTBTeam/FTB-Academy/files/4112868/crash-2020-01-25_23.23.09-client.txt)

**Comment by aaronhowser1** [comment]
Use a different Launcher

**Comment by Kimodd** [comment]
You mean something  besides Twitch ?

**Comment by aaronhowser1** [comment]
Yes, like the [FTB Launcher](https://www.feed-the-beast.com/).
