### ISSUE TITLE
Ender Tank/Chest triggering the quest completion for Chest/Tank

### ISSUE THREAD

**Issue by nandi910** [FTBTeam/FTB-Academy#25]
* **Modpack Version**: Recommended

* **Issue**: Crafting an Ender Tank also completes Ender Chest quest in the quest book.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes, created a new map and it behaves the same way.

* **Mod/s Affected**: Ender Chest and FTBQuest

* **Known Fix**: A way to fix it could be to also check the variant of the block, not just the ID of it since Ender Chests and Ender Tanks are on the same ID but different variants.

**Comment by aaronhowser1** [comment]
It's probably  because they're separated by metadata only, using the same block id. I have it set to ignore metadata and nbt, I need to set it to only ignore nbt
