### ISSUE TITLE
cant see all quests

### ISSUE THREAD

**Issue by dzh121** [FTBTeam/FTB-Academy#250]
* **Modpack Version**1.1.1

* **Issue**: the quests dont show up after i reach them, i did all the storge quests i can but still the quests is only at 38%

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: its happing in couple of quests type

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
You likely haven't unlocked the rest of the storage quests. There are quests that depend on quests from other chapters. Type the command `/ftbquests editing_mode` to see them (then type the command again to go back to normal gameplay).

**Comment by dzh121** [comment]
yeh i did that when i went back it still didnt show

**Comment by aaronhowser1** [comment]
Of course it didn't show up after you went back out of editing mode. You went out of editing mode. That means you can't see hidden quests, because you aren't in editing mode. You need to unlock them first, by completing quests in other chapters.

**Comment by dzh121** [comment]
thanks

**Comment by dzh121** [comment]
i did athor quests and then its showed up
