### ISSUE TITLE
It's super easy to plant the petals in the botania tutorial

### ISSUE THREAD

**Issue by SwiftlySwift** [FTBTeam/FTB-Academy#251]
* **Modpack Version**: 
1.1.0
* **Issue**: 
You you're in the botania tutorial it's pretty easy to right click the petals on the ground instead of dropping them, especially since this is the first time anything operates on drop mechanics instead of right clicks.

* **Is it Repeatable?**: 
Yes

* **Known Fix**: 
Put a box of extra petals nearby once you craft the plants into petals, just in case.

**Comment by aaronhowser1** [comment]
Already fixed for 1.2
