### ISSUE TITLE
Server mod rejections

### ISSUE THREAD

**Issue by calc519** [FTBTeam/FTB-Academy#252]
<
I've added nothing to the modpack and whenever i check in installed mods its only the mods which are part of the pack but when i try to join my friends server i get a list of mod rejections which i don't even have.
-->

* **Modpack Version**: <1.0.0>

* **Issue**: <  Whenever i try to join my friends server i get an error they says all the mod rejections but none of them are in my files or part of the modpack  >

* **Is it Repeatable?**: <Yes, every time i try to join the server>

* **Known Fix**: <None>
![IMG_1926](https://user-images.githubusercontent.com/60449184/73397252-178d4400-42b1-11ea-9fdb-7365d1c75355.jpg)

**Comment by aaronhowser1** [comment]
Stop playing 1.0.0, first of all.

Reinstall the modpack on server and client, the *most up to date version*.

**Comment by aaronhowser1** [comment]
WAIT A SECOND

**Comment by aaronhowser1** [comment]
THATS NOT EVEN ACADEMY'S MOD LIST!

Academy has never had Admin Weapons, Environmental Tech, Galacticraft, or any of those other mods. The server is using an entirely different modpack!
