### ISSUE TITLE
Tutorial loaded after account change.

### ISSUE THREAD

**Issue by BLackHorror555** [FTBTeam/FTB-Academy#253]
* **Modpack Version**: 1.1.1

* **Issue**: Hi from Russia! I was playing this modpack 2 months ago and now decide to continue. But I have to change mojang account. So, I load my saved game and suddenly appeared at the very beginning of training but with all my items in inventory. Is it expected behaviour when account changed? What should I do to continue to play from my last save?
I've tried to quit the tutorial, but it starts clean new game.

Thanks in advance.

* **Is it Repeatable?**: Yes, all my backups behave in that way

**Comment by Sunekaer** [comment]
Yes this is expected behavior, as all quests and inventory is save in the world to your other account

**Comment by BLackHorror555** [comment]
So I can't recover data somehow without an old account?

**Comment by aaronhowser1** [comment]
You probably could edit the world's nbt and change your old username to your new one maybe

**Comment by BLackHorror555** [comment]
@aaronhowser1 I'm try it, thanks a lot

**Comment by aaronhowser1** [comment]
Extreme edge case with known manual fix, impossible to automate
