### ISSUE TITLE
I can't open any worlds

### ISSUE THREAD

**Issue by BelleBearxxx** [FTBTeam/FTB-Academy#256]
* **Modpack Version**: 1.1.0
* **Issue**: Hi! I'm a first time user of FTB. Everthing is fine until I create or open a world, then it crashes and says there was an unknown error. It doesnt say it was caused by a specific mod.

* **Link to Log or Crash File Paste**: https://paste.dimdev.org/xanisasere.mccrash

* **Is it Repeatable?**: yes

**Comment by aaronhowser1** [comment]
Do you have shaders or anything installed? If not, try completely reinstalling the modpack using the FTB Launcher

**Comment by BelleBearxxx** [comment]
I don't have any shaders, but I downloaded the modpack using twitch and it worked fine.

**Comment by BelleBearxxx** [comment]
No, I don't. I installed the pack using twitch and it is now working.
