### ISSUE TITLE
Server Update!!

### ISSUE THREAD

**Issue by Jlixn** [FTBTeam/FTB-Academy#258]
* **Modpack Version**: FTBAcademy-1.1.1-1.12.2

* **Issue**: wanted to start an server on the newer modpack version but then i realized the server files arent updated

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: -

* **Mod/s Affected**: the server

* **Known Fix**: -

**Comment by aaronhowser1** [comment]
1.1.1 is a client side only update, use the 1.1.0 server files

**Comment by Jlixn** [comment]
It doesn't exist 1.1.0 server files, only 1.0.0

**Comment by Jlixn** [comment]
SERVER FILE LINK FOR OTHER USERS
Version: 1.1.0
[](https://www.curseforge.com/minecraft/modpacks/ftb-academy/files/2792369)

**Comment by aaronhowser1** [comment]
https://www.curseforge.com/minecraft/modpacks/ftb-academy/files/2792369
