### ISSUE TITLE
game always crashes when i load my world

### ISSUE THREAD

**Issue by jokerdarkclan** [FTBTeam/FTB-Academy#259]
I've been playing the modpack for a few days and it just crashed.
This is the report:

https://paste.dimdev.org/vehahexuco.mccrash

I've already tried restarting it but it doesn't work
and I downloaded it from twitch

**Comment by James103** [comment]
I can't access the crash log (see DimensionalDevelopment/VanillaFix#262). Could you please try reuploading the crash report to Gist or Pastebin without any expiry dates?
