### ISSUE TITLE
Not downloading in GDLauncher

### ISSUE THREAD

**Issue by Variable-X** [FTBTeam/FTB-Academy#26]
* **Modpack Version**: 1.0.0

* **Issue**: Download goes on without starting. After a while, if you cancel the download it will create an empty folder called FTBAcademy. However, I can download other FTB modpacks just fine.

* **Link to Log or Crash File Paste**: Unknown

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Unknown

* **Known Fix**: Unknown

**Comment by aaronhowser1** [comment]
Likely the same problem as MultiMC's forge issue. Open the manifest.json, and change "modloader" to "modLoader" and see if that fixes it.

**Comment by Sunekaer** [comment]
#13

**Comment by Variable-X** [comment]
Do you know where the file would be? I can't find it in roaming GDLauncher or the actual install location.
