### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by Illica** [FTBTeam/FTB-Academy#260]
* **1.10** 

* **Modpack downloads almost fully, stalls for a moment before finishing, then fails to launch.** 

* **https://paste.feed-the-beast.com/view/f4b7b233** 

* **Occurs every attempt at launching**

**Comment by aaronhowser1** [comment]
I googled `java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker` and found [this page](https://gist.github.com/jikuja/7e0828dca7d264e850be306b58893127). Try doing this:
![image](https://user-images.githubusercontent.com/15698722/74476742-9f597d80-4e6f-11ea-9638-46aec8196c02.png)
