### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by eslachance** [FTBTeam/FTB-Academy#261]
* **Modpack Version**: 1.1.0 (FTB Launcher)

* **Feature Request**: Add timers/detectors/logic mod to help in Canola automation, and accompanying tutorial

As a long-time player evaluating this pack to introduce minecraft beginners to modding, there are few things I'm very much used to doing. For example, an automated tree farm (here replaced by bonsai), a proper storage system (refined storage helps a lot), good tools (TiC is perfect), etc. 

What seems to be missing in this pack is the type of mod that helps with some specific automations, most notably, the apparent lack of detectors, timers, circuit systems, etc. There's no integrated dynamics, no SuperCircuitMaker-type mod, no RFUtilities, no Extra Utilities. This became immediately apparent when I attempted to automate canola processing: there was no tutorial I could see in the quest book even though I was at the perfect tech level, there was no apparent detector to trigger on crystallized oil, no redstone circuits to trigger the dropper, etc. It's easy enough to pick up the oil using Refined Storage, but no way to stop the dropped from wasting all the seeds by dropping them.

Perhaps Project Red, some logic gates? EnderIO, RFTools, Extra Utilities? All very useful mods overall, but specifically for this purpose, also very useable. 

*Thanks for coming to my TED Talk!*

**Comment by aaronhowser1** [comment]
The Guide has a fairly in depth step by step tutorial for Canola, it has
pictures and everything. All you need is a Hovering Hourglass for a timer
and some vanilla Redstone.

**Comment by eslachance** [comment]
I wouldn't consider vanilla redstone and an hourglass to be a proper method of automating canola energizing, feeding seeds into only regular canola, etc... On top of which, there are plenty of other situations where automation using something like Integrated Dynamics would make things easier.

**Comment by Venom31** [comment]
Thermal Expansion structural ducts with relays help a lot in redstone wiring. Just make sure you don't move them with vanilla pistons, that may crash your game.
