### ISSUE TITLE
Volume keys set off unbound controls

### ISSUE THREAD

**Issue by Kopilot98** [FTBTeam/FTB-Academy#263]
Hi together, Iam playing FTBAcademy and using the play- and pause-keys on my keyboard for background music, but every time press this keys the MineTogether Chat options open. Can someone help me to rebind the keys or switch it off ?

**Comment by aaronhowser1** [comment]
For some reason those and the volume keys set off any unbound controls. Find them in the controls menu and rebind them to anything else, like numpad minus

**Comment by aaronhowser1** [comment]
Fixed with mod update
