### ISSUE TITLE
My main world suddenly dissapeared

### ISSUE THREAD

**Issue by VVilsonPH** [FTBTeam/FTB-Academy#265]
* **Modpack Version**: FTB Academy v.1.1.0

* **Issue**: Even though nothing has happened with the folder of said world, Minecraft can no longer see it. Deleting it, restarting the game, putting in back and restarting the game again didn't help.

**Comment by aaronhowser1** [comment]
It could be corrupt, try loading from a backup

**Comment by VVilsonPH** [comment]
Unfortunately I don't have any backups

**Comment by aaronhowser1** [comment]
Are you sure? A backup should be made every two hours automatically, in a folder in the main modpack folder called /backups/
