### ISSUE TITLE
I cant start a new world after downloading the academy modpack

### ISSUE THREAD

**Issue by Ndknkasnkd12** [FTBTeam/FTB-Academy#267]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Ndknkasnkd12** [comment]
oh oops

**Comment by Ndknkasnkd12** [comment]
okay lemme try again 
the modpack version is the most recent version
the issue: i cant seem to load up a new world 
https://paste.dimdev.org/volabiboci.mccrash
yeah i cant play at all since i cant start a new world
unknown

**Comment by aaronhowser1** [comment]
Try reinstalling the pack. If you added or removed any mods, try without them.
