### ISSUE TITLE
Tutorial loaded after i copied a world

### ISSUE THREAD

**Issue by Alextitanfind** [FTBTeam/FTB-Academy#268]
Hi, i start by saying sorry for my bad english.
Today i was playing as usual, everything went good since i closed the game... i opened it again like 3 hours later and the game didn't loaded at all, it was freeze at the screen with minecraft "launching"... so i decided to copy my world, unistall the entire modpack and re-install it (through twitch)
Now i can launch the game and also play but when i copied my world, the game loaded into the tutorial, with my old inventory, and also the quest book. i tought i could do again the tutorial and then play again, but all the first missions were already done, of course... i also had the item (i dont remember the name) that you link it in a place and if you press it, it will teleport you in that coordinates... i used it (it was linked inside my house) it teleported me, but now i cant break any block
I don't want to restart a new world, i was far in the game...
Please help me 
thank you

**Comment by Alextitanfind** [comment]
modpack version 1.1.1

**Comment by Barberfluids** [comment]
I had this issue.  How did you get around it?
