### ISSUE TITLE
General Guide translation questions

### ISSUE THREAD

**Issue by nikitasA1NT** [FTBTeam/FTB-Academy#269]
For a full Russian translation, it remains only to translate the guide? Please describe how to do this correctly, I'm afraid I misunderstood. Maybe I'll do it in my free time

**Comment by aaronhowser1** [comment]
I'll copy the blurb from the [Code page](https://github.com/FTBTeam/FTB-Academy):

> The guide is a bit more involved to translate, as it doesn't use language keys. Copy the entire /config/ftbguides/modpack_guide/ folder and rename it, adding the language to the end (so for Russian, it would be /modpack_guide_ru_ru/). Missing files will default to the regular modpack_guide folder, which means you can delete images from the translated folder safely (unless you want to retake them to translate any text it has in it). To rename pages, open up the index.jsons and translate the text labeled title only. Leave the ids and folders the way they are now, they won't be seen by the player. The meat of the guide is in the README.md files; translate them however you want, just try to keep them similar to the English versions.

So basically, if the language is set to Russian, it'll try to use whatever's in `/modpack_guide_ru_ru/`. If there's a file missing from that, it'll use the `/modpack_guide/` version. That means you don't have to copy images, unless you want to retake the screenshots with the language changed or something.

**Comment by nikitasA1NT** [comment]
Ok. And to translate the text of the guides, you just need to translate the text of the README.md files?

**Comment by aaronhowser1** [comment]
Yes, you would make a README.md file in the same relative file location as the English version (meaning both are in, like, /technology/ in both English and Russian) and put the translated text there.

**Comment by nikitasA1NT** [comment]
`#Building Gadget
![Building Gadget](item:buildinggadgets:buildingtool)
Строительный гаджет позволяет быстро создавать простые конструкции, такие как стены и лестницы.
Нажмите правой кнопкой мыши на блок, чтобы установить гаджет, чтобы построить этот блок, и щелкните правой кнопкой мыши, чтобы построить там, где отображается голограмма.

Building Modes
![](buildtome.png)
The Build to Me mode will attempt to make a straight line of blocks from where you're pointing to you.`

Do I need to translate lines:
#Building Gadget
...
Building Modes

**Comment by aaronhowser1** [comment]
Yes. # means that line is big, like a title. So it would look like this, according to Google Translate: `#Строительные гаджеты`.

**Comment by nikitasA1NT** [comment]
I probably somehow did something wrong on GitGub, I just recently started using it. In general, translations can be found in my repositories. If it is successful, how will it be added to modpack later?

**Comment by aaronhowser1** [comment]
You would make a pull request. Honestly, I don't know enough about GitHub to tell you how to do that though, sorry.

 /pull/255 is working on Russian quest translations, so maybe ask them.

**Comment by nikitasA1NT** [comment]
When I finish the text translation, how can I put it on modpack later?

**Comment by aaronhowser1** [comment]
What do you mean? Like, how do you send it to us for us to put it in the modpack officially?

**Comment by nikitasA1NT** [comment]
Either this, or if it is impossible, then I can put it on the downloaded modpack on my computer.

**Comment by aaronhowser1** [comment]
Well it would already be in the downloaded modpack on your computer, since you're the one making it. I'm not really sure what you're asking. If you want to send it to us when you're done, you would make a pull request here.

**Comment by nikitasA1NT** [comment]
Я делаю перевод не в папке скачанного модпака, а в скачанной отсюда папке modpack_guide и переименованной мною в modpack_guide_ru_ru. Когда я закончу работу, мне нужно переместить эту папку рядом с папкой modpack_guide в модпаке?

**Comment by nikitasA1NT** [comment]
I do not translate in the folder of the downloaded modpack, but in the folder modpack_guide downloaded from here and renamed me modpack_guide_ru_ru. When I finish work, do I need to move this folder next to the modpack_guide folder in the modpack?

**Comment by aaronhowser1** [comment]
Download the `modpack_guide` [here](https://github.com/FTBTeam/FTB-Academy/archive/master.zip), rename it to `modpack_guide_ru_ru`, put it in /config/ftbguides/, do the translation stuff, and that's it (aside from sending it to us).

**Comment by aaronhowser1** [comment]
Please be aware of the changes made in https://github.com/FTBTeam/FTB-Academy/commit/8b1c694eea0021acaac07ba79fa143298e6008cf
