### ISSUE TITLE
Modpack Manifest File is Corrupted – Pack Does Not Install

### ISSUE THREAD

**Issue by Compsogbrickus** [FTBTeam/FTB-Academy#27]
* **Modpack Version**: FTBAcademy-1.0.0-1.12.2

* **Issue**: It looks like this has been reported a couple times and incorrectly closed. When installing the modpack, I get an error that looks something like this:
`Access to the path "/var/folders/qs/_r7cznp57_g0s3jnggy_p02r0000gp/T/Curse Client/[Log ID for Twitch Launch]/[some number]/manifest.json" or "/Users/[user]/Twitch/Minecraft/Instances/FTB Academy/manifest.json" is denied.`
I initially worked through Twitch support to figure out if it was a problem on my end, but while I would say their suggestions were cute, they didn't change the issue.

The issue is, as far as I can tell, that something about the values in the Manifest is wrong, leading the file to be rejected by the installer as non-existent. This is wrong. The file does appear very briefly, but is immediately deleted. It is partially processed, then spit out, as confirmed by copying the overrides file into the /var/.../[some number]/ path (this partially installs and then throws more of the same error into the log).

As suggested by users of other launchers, this appears to caused be a typo in the Manifest. This can be confirmed by cross-referencing the Manifest with other FTB packs.

I am on a 2017 15" Macbook Pro with macOS 10.14.6.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/9e9aa37a
Please note that to protect my identity I have replaced my user space with [user]. This is from a completely clean install of the Twitch Desktop App.

* **Is it Repeatable?**: Yes, on my machine.

* **Mod/s Affected**: N/A (Possibly Forge)

* **Known Fix**: Replace `l` with `L` at position 6148 in `manifest.json`

**Comment by Sunekaer** [comment]
#7

**Comment by Compsogbrickus** [comment]
This is not a launcher issue. Please see #26. If you are in Windows and trying to duplicate this, case-sensitivity needs to be enabled. It should be possible through a new install or a VM.

**Comment by Compsogbrickus** [comment]
Is there a way for me (the user) to patch the ccip package so I can use the pack through the official launcher (Twitch Desktop App)?
