### ISSUE TITLE
Error in english lang file at line 749

### ISSUE THREAD

**Issue by Cheos137** [FTBTeam/FTB-Academy#272]
* **Modpack Version**: current dev version (post 1.1.0)

* **Issue**: ``For instance, export Redstone Dust into a Magma Crucible only when given a Redstone    signal, and place a Detector down that only emits the signal if you have under 50 buckets of   Destabilized Redstone. That way, you'll always have at least 50 buckets of Destabilized Redstone in the system at all times.``
  should say
  ``For instance, export Redstone Dust into a Magma Crucible only when given a Redstone signal, and place a Detector down that only emits the signal if you have`` **``over``** ``50 buckets of Destabilized Redstone. That way, you'll always have at least 50 buckets of Destabilized Redstone in the system at all times.``
  to make sense.

**Comment by aaronhowser1** [comment]
`export Redstone Dust into a Magma Crucible only when given a Redstone signal`
That means it only melts the dust if it has under 50B of Destabilized Redstone. The Detector is pointing at the Exporter, not the Magma Crucible.
