### ISSUE TITLE
GM Chicken Feed - Missing JEI Recipe

### ISSUE THREAD

**Issue by jozef-mitro** [FTBTeam/FTB-Academy#277]
* **Modpack Version**: 1.2.0

* **Issue**: GM Chicken Feed doesn't have recipe in JEI. Crafting it according to instructions from Mob Grinding Utils (seeds + mob swab + bucket of experience) works. Perhaps because some mob swab metadata oddity (recipe uses mob swab containing specific mob dna)? If it's not easily fixable at least adding recipe to the Kind of Horryfing Actually quest description might help players who are not that good at googling.

* **Is it Repeatable?**: Happens in every world I create. I haven't tried reinstalling the pack yet.

**Comment by aaronhowser1** [comment]
Good catch! Added a JEI info page to it.
