### ISSUE TITLE
Slime Boots and Slimesling Made of Actually Additions Rice Slimeball don't register for the "Up and Down, Up and Down" Quest

### ISSUE THREAD

**Issue by jozef-mitro** [FTBTeam/FTB-Academy#278]
* **Modpack Version**: 1.2.0

* **Issue**: Using Rice Slimeball (id 6293/12) creates Slime Boots (id 5879/5) and Slimesling (id 5878/5) as if made of Slimeball (id 5758/5, Nausea variant). These item do not register for the quest completion (though they're not on the quest list in the first place so...). None of the /5 line of slime items shows up in the JEI search either even though their recipes work normally and they show up when hitting U on Rice Slimeball. Not sure if this is fixable and probably not a huge issue since there are other more proper ways of getting those items but I thought I would mention it.

**Comment by aaronhowser1** [comment]
Apparently those are the fallback versions, I had no idea those even existed. Fixed for the next version though, thanks!
