### ISSUE TITLE
Questing issues

### ISSUE THREAD

**Issue by ethanryan12** [FTBTeam/FTB-Academy#279]
* **Modpack Version**: 1.0.0

* **Issue**: I was crafting the smeltery, it registered 16 bricks but after that, it stopped working, I've tried many methods of crafting and the other quests work. I have no idea how to update the mod pack.

* **Is it Repeatable?**: no

**Comment by aaronhowser1** [comment]
Update to 1.2.0

**Comment by ethanryan12** [comment]
I told you, I can't update or don't know how to, I've tried changing the version to 1.2.0 and clicking the repair button but it stayed on 1.0.0

**Comment by ethanryan12** [comment]
restarting twitch seems to have fixed the issue of updating, I loaded the world well it was updating and therefore caused it to load the world without mods so it's a broken save and well yeah. In other news, I can't find the 2.0 version on twitch.

**Comment by ethanryan12** [comment]
Must be because of the end of the partnership, I'm a bit bitter that FTB can't keep uploading their modpacks to twitch but it's time to move on

**Comment by aaronhowser1** [comment]
1.2 and all future updates will only be on FTB Launcher. We didn't choose to sever ties with Curseforge, that was Twitch. Sorry for the inconvenience.
