### ISSUE TITLE
In-World tutorial texts overlapping when playing in creative mode

### ISSUE THREAD

**Issue by Cheos137** [FTBTeam/FTB-Academy#28]
* **Modpack Version**: 1.0.0

* **Issue**: When switching to creative mode via commands, some of the arrows on the floors/texts in the air are overlapping.

* **Link to Log or Crash File Paste**: no crash, no report.

* **Is it Repeatable?**: Yes. By switching to creative mode while in the Academy area

* **Mod/s Affected**: none

* **Known Fix**: It surely is not intended to switch to creative mode in the Academy area so maybe preventing the player from switching gamemode in the Academy area would be a solution.

![2019-08-24_19 21 01](https://user-images.githubusercontent.com/54480514/63641107-47547200-c6a9-11e9-9b82-12f9f2e00ee0.png)
![2019-08-24_19 21 13](https://user-images.githubusercontent.com/54480514/63641108-47547200-c6a9-11e9-8291-ce080d9713c9.png)
![2019-08-24_19 20 48](https://user-images.githubusercontent.com/54480514/63641109-47547200-c6a9-11e9-8f5d-53ab0d7a35d1.png)
![2019-08-24_19 20 53](https://user-images.githubusercontent.com/54480514/63641110-47ed0880-c6a9-11e9-9ab1-7ed2065557fd.png)

**Comment by Sunekaer** [comment]
Not a bug.
All banners show's when in creative.

**Comment by aaronhowser1** [comment]
How did you even do this? I thought commands were disabled until you left the school.

**Comment by Cheos137** [comment]
I simply created a new world with cheats enabled and switched to creative mode (via chat commands).

**Comment by Sunekaer** [comment]
there only a few commands in school that work
