### ISSUE TITLE
Refined Taste automatically completes Ok, It's Getting Bit Old Now

### ISSUE THREAD

**Issue by jozef-mitro** [FTBTeam/FTB-Academy#282]
* **Modpack Version**: 1.2.0

* **Issue**: Creating a bucket of refined canola oil for the Refined Taste quest automatically completes the next quest in the line Ok, It's Getting Bit Old Now which requires a bucket of crystallized oil. I suspect this is due to buckets having same id and metadata just different nbt?

* **Is it Repeatable?**: Yes. Create new world progress down the Actual Additions quests by spawning right items.

**Comment by aaronhowser1** [comment]
Yep, the Crystallized Oil quest ignored NBT so it accepted literally any filled bucket. Fixed for next version!
