### ISSUE TITLE
"Injecting burger directly into your veins" quest reward gives empty portable tank

### ISSUE THREAD

**Issue by jozef-mitro** [FTBTeam/FTB-Academy#284]
* **Modpack Version**: 1.2.0

* **Issue**: "Injecting burger directly into your veins" quest reward gives empty portable tank instead of what's shown on the quest page (one filled with liquid meat).

**Comment by Venom31** [comment]
The Meat Feeder automatically drinks Liquid Meat from any and all portable tanks and reservoirs in your inventory. So please make sure you didn't put it into some bauble slot. If you did, the Liquid Meat from portable tank is probably there, feeding you until it runs out.

**Comment by aaronhowser1** [comment]
Wait does it? I had no idea @Venom31

**Comment by Venom31** [comment]
Yes, but Ender Tanks seem to not be affected atm.

**Comment by aaronhowser1** [comment]
Probably because the rank itself doesn't actually store any fluid. The only
nbt it has is the color combo etc, the fluid amount is probably stored in a
list somewhere else in the world folder.

**Comment by jozef-mitro** [comment]
I can test later today but I'm pretty sure it was the meat feeder drinking it and me not noticing. Working as intended then.
