### ISSUE TITLE
1.12 Rail duper and tinker smeltery glitch(game breaking infinite iron and gold)

### ISSUE THREAD

**Issue by lamshiu** [FTBTeam/FTB-Academy#286]
You  can use the vanilla 1.12 rail duper to dupe the powered rail and rail, then smelt it to iron or gold in the smeltery provide by TConstruct-1.12.2-2.13.0.183   . This method can be used to produce a huge amount of irons and golds and use for various purposes.  

* **Modpack Version**:Ftb academy 1.2.0 (or lower)

* **Issue**: Rail duping+tinker smelter glitch for infinite iron and gold

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes 

* **Mod/s Affected**: TConstruct-1.12.2-2.13.0.183 

* **Known Fix**:  upgrade TConstruct to newer version

![2020-04-11_14 10 03](https://user-images.githubusercontent.com/63488704/79036959-d8a83280-7bff-11ea-836b-ff81f141c9af.png)
![2020-04-11_14 15 23](https://user-images.githubusercontent.com/63488704/79036962-e52c8b00-7bff-11ea-8fa2-37ffd17a0160.png)
![2020-04-11_14 17 40](https://user-images.githubusercontent.com/63488704/79036967-ed84c600-7bff-11ea-9d0b-fe26c1f65fe3.png)
![2020-04-11_14 18 09](https://user-images.githubusercontent.com/63488704/79036976-f5dd0100-7bff-11ea-8ae2-0584cf491b55.png)
![2020-04-11_14 18 42](https://user-images.githubusercontent.com/63488704/79036980-fe353c00-7bff-11ea-9d51-5d7de9cdfb85.png)

Reference for 1.12 rail duper
[https://www.youtube.com/watch?v=NXRWzHPMI0A](url)

**Comment by aaronhowser1** [comment]
This is a vanilla issue, we can't really fix it. It's also super obscure, so I don't think it's worth worrying too much over.

**Comment by aaronhowser1** [comment]
> Known Fix: upgrade TConstruct to newer version

TiCon is also on the latest current version.

**Comment by lamshiu** [comment]
Oh yea I'm sorry, I remember I played a pack and the rails cannot be smelted .I think that is an old version of tinker, so it's ok .
