### ISSUE TITLE
Game crashes once i try to launch from FTB App

### ISSUE THREAD

**Issue by derpbenji** [FTBTeam/FTB-Academy#291]
Version: 1.2.0

My game crashes as soon as i try to launch the game from the minecraft launcher. 

https://paste.feed-the-beast.com/view/ce0b699a

 if you know of a fix please let me know! Thanks

**Comment by aaronhowser1** [comment]
This is a launcher problem, please post this at https://github.com/FTBTeam/FTB-App/issues
