### ISSUE TITLE
just updated FTB Academy Server not recognising new version of XPTeleporters-1.12.2-2.0.2.jar and thereby will not load

### ISSUE THREAD

**Issue by Elderwolf569** [FTBTeam/FTB-Academy#292]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Is this on the FTB App or Twitch?

**Comment by wheetcracker** [comment]
The fix is really simple. Just drop the 2.0.2 jar into your server's mods folder. Make sure to delete the 2.0.1 jar as well.

Here's the jar: https://www.curseforge.com/minecraft/mc-mods/xpteleporters-2/files/2827714
