### ISSUE TITLE
Server Files not compatibiliti witch client...

### ISSUE THREAD

**Issue by ilijaakovic123** [FTBTeam/FTB-Academy#294]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by ilijaakovic123** [comment]
image: https://instagram.fbeg2-1.fna.fbcdn.net/v/t51.2885-15/e35/93655440_1281547038702456_388638454663148458_n.jpg?_nc_ht=instagram.fbeg2-1.fna.fbcdn.net&_nc_cat=100&_nc_ohc=cunSAJz82RoAX_SRwuO&oh=627b23b9bff50ac7ab5e0698f879b1c5&oe=5EC64819&ig_cache_key=MjI5MTExODk1MzQyNjM0NzI2Nw%3D%3D.2

**Comment by aaronhowser1** [comment]
The server is using a different version of the modpack than you. Looks like the server is outdated, since its mods are a lower version than yours.
