### ISSUE TITLE
no iron block in tutorial starting area

### ISSUE THREAD

**Issue by tristenator** [FTBTeam/FTB-Academy#295]
hello, about 60 seconds into the tutorial i could not progress because there wasn't an iron block in storage (quantity was zero).

another issue: the crafting table was not rewarded to me as a result of completing "Learn to use JEI".

so then i thought ok  i'll craft a crafting table (from the wood provided in storage) and craft an iron block using the nuggets/iron but i could not place a block in the area.

because everything is gated i'm sad to say that's pretty much game over almost as soon as it starts.

version: 1.2.0 (single player)

tutorial: "bulk storage"

crash info (n/a)

it is repeatable, i started again with a new world, and the iron block was still not there (quantity: 0)

i don't know if a specific mod causes the problem or not.

workaround: i deleted the world, created a new one with cheats enabled, progressed to "bulk storage", spammed in an iron block, as soon as the iron block popped into my inventory the tutorial item completed and i was able to progress. to the

**Comment by aaronhowser1** [comment]
Read the quest text. Put the iron nugget in the drawer, and THEN take out an iron block/

**Comment by tristenator** [comment]
beg pardon!
