### ISSUE TITLE
MineTogether crashes minecraft

### ISSUE THREAD

**Issue by joao44289** [FTBTeam/FTB-Academy#296]
* **Modpack Version**: <1.2>

* **Issue**: Game crashes when trying to talk on minetogether

* **Link to Log or Crash File Paste**: <https://pastebin.com/fBw1jMwC>

* **Is it Repeatable?**: yes

* **Mod/s Affected**: MineTogether

* **Known Fix**: None so far, tried updating the mod but that only made it worse

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/80320804-2e730200-87de-11ea-8b23-70563fc0beb6.png)
