### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by whitejerry20** [FTBTeam/FTB-Academy#297]
1.1.2

* **Issue**: crashed a few times while mining looked like about a chunk turned into dark oak buttons 

* **Link to Log or Crash File Paste**: failed to get link

* **Is it Repeatable?**:  yes re logged and was still there 

* **Mod/s Affected**: unk

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Update to 1.2.0

**Comment by aaronhowser1** [comment]
Also if your chunk turned into dark oak buttons, your world may be corrupted. Load a backup
