### ISSUE TITLE
Request/Enhancement/Sugestion: More Overlays

### ISSUE THREAD

**Issue by Iplay2L8** [FTBTeam/FTB-Academy#30]
Adding a  tutorial quest for _More Overlays_. Many new to modding do not know how handy it is.

* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
They're in the guide, under Your Interface
