### ISSUE TITLE
Watering Can quest doesn't complete

### ISSUE THREAD

**Issue by koenvanzuijlen** [FTBTeam/FTB-Academy#302]
* **Modpack Version**: 1.2.0

* **Issue**: The watering can quest in the miscellaneous section won't complete. I've tried both a full and empty one but neither works.

**Comment by koenvanzuijlen** [comment]
This can be closed, turns out this was the only quest in the whole modpack which needed to submit the item.

**Comment by aaronhowser1** [comment]
Oh really? Weird. Sorry I haven't had a chance to work in Academy in a while, working on Uni.

I have vague memories of this quest giving a higher tier one as a reward. Is that true? If so, I'll edit the description.
