### ISSUE TITLE
MineTogether chat is empty

### ISSUE THREAD

**Issue by VVilsonPH** [FTBTeam/FTB-Academy#307]
* **Modpack Version**: v1.2.0

* **Issue**: After geting the "<System> Disconnected (Reason :BanniusHammerius! CreeperHost@noc.as201971.net MODE #superspecialpirateclub). Recconecting" message the MineTogether chat stopped displaying any messages, even the ones I typed. After restarting the game the chat remained empty.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: MineTogether

* **Known Fix**: None so far

**Comment by aaronhowser1** [comment]
If you got banned, you'll have to ask [here](https://github.com/CreeperHost/CreeperHostGui/issues).
