### ISSUE TITLE
Crash seemingly caused by quest completion.

### ISSUE THREAD

**Issue by EDDIEWAKOWSKI** [FTBTeam/FTB-Academy#31]
* **Modpack Version**: FTB Academy 1.0.0

* **Issue**: Client crashing anytime a quest is completed and achievement bell sounds.

* **Link to Log or Crash File Paste**:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  LoadingPlugin (splashlogofix-1.0.jar)
  StructureUtilsASM (StructureUtils-1.1.0.4.jar)
  AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 8/25/19 2:03 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.loadText(QuestObjectBase.java:195)
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getTitle(QuestObjectBase.java:304)
	at com.feed_the_beast.ftbquests.gui.ToastQuestObject.getSubtitle(ToastQuestObject.java:33)
	at com.feed_the_beast.ftblib.lib.gui.misc.SimpleToast.func_193653_a(SimpleToast.java:32)
	at net.minecraft.client.gui.toasts.GuiToast$ToastInstance.func_193684_a(SourceFile:115)
	at net.minecraft.client.gui.toasts.GuiToast.func_191783_a(SourceFile:35)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1121)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.loadText(QuestObjectBase.java:195)
	at com.feed_the_beast.ftbquests.quest.QuestObjectBase.getTitle(QuestObjectBase.java:304)
	at com.feed_the_beast.ftbquests.gui.ToastQuestObject.getSubtitle(ToastQuestObject.java:33)
	at com.feed_the_beast.ftblib.lib.gui.misc.SimpleToast.func_193653_a(SimpleToast.java:32)
	at net.minecraft.client.gui.toasts.GuiToast$ToastInstance.func_193684_a(SourceFile:115)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['UnusualComet'/302, l='MpServer', x=284.47, y=76.00, z=292.84]]
	Chunk stats: MultiplayerChunkCache: 380, 380
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 16320 game time, 16320 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 4 total; [EntityLatchedRenderer['unknown'/305, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/306, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/308, l='MpServer', x=284.47, y=76.00, z=292.84], EntityPlayerSP['UnusualComet'/302, l='MpServer', x=284.47, y=76.00, z=292.84]]
	Retry entities: 2 total; [EntityLatchedRenderer['unknown'/305, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/306, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 568036776 bytes (541 MB) / 3500670976 bytes (3338 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -Xmx8192m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 119 mods loaded, 119 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                  | Source                                             | Signature                                |
	|:------ |:----------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                     | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | smoothfontcore          | mc1.12.2-2.1             | minecraft.jar                                      | None                                     |
	| LCHIJA | foamfixcore             | 7.7.4                    | minecraft.jar                                      | None                                     |
	| LCHIJA | dsurroundcore           | 3.5.4.3                  | minecraft.jar                                      | None                                     |
	| LCHIJA | randompatches           | 1.12.2-1.17.2.1          | randompatches-1.12.2-1.17.2.1.jar                  | None                                     |
	| LCHIJA | smoothfont              | mc1.12.2-2.1             | SmoothFont-mc1.12.2-2.1.jar                        | None                                     |
	| LCHIJA | fastbench               | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                     | None                                     |
	| LCHIJA | actuallyadditions       | 1.12.2-r149              | ActuallyAdditions-1.12.2-r149.jar                  | None                                     |
	| LCHIJA | crafttweaker            | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
	| LCHIJA | mtlib                   | 3.0.6                    | MTLib-3.0.6.jar                                    | None                                     |
	| LCHIJA | modtweaker              | 4.0.17                   | modtweaker-4.0.17.jar                              | None                                     |
	| LCHIJA | jei                     | 4.15.0.287               | jei_1.12.2-4.15.0.287.jar                          | None                                     |
	| LCHIJA | appleskin               | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| LCHIJA | baubles                 | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | astralsorcery           | 1.10.20                  | astralsorcery-1.12.2-1.10.20.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | quark                   | r1.6-177                 | Quark-r1.6-177.jar                                 | None                                     |
	| LCHIJA | autoreglib              | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA | ichunutil               | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | backtools               | 7.0.1                    | BackTools-1.12.2-7.0.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | betterbuilderswands     | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar  | None                                     |
	| LCHIJA | bonsaitrees             | 1.1.3                    | bonsaitrees-1.1.3-b156.jar                         | None                                     |
	| LCHIJA | bookshelf               | 2.3.585                  | Bookshelf-1.12.2-2.3.585.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | botania                 | r1.10-361                | Botania r1.10-361.jar                              | None                                     |
	| LCHIJA | codechickenlib          | 3.2.3.357                | CodeChickenLib-1.12.2-3.2.3.357-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux            | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | brandonscore            | 2.4.17                   | BrandonsCore-1.12.2-2.4.17.208-universal.jar       | None                                     |
	| LCHIJA | buildinggadgets         | 2.7.2                    | BuildingGadgets-2.7.2.jar                          | None                                     |
	| LCHIJA | chameleon               | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | ctm                     | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| LCHIJA | chisel                  | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LCHIJA | clumps                  | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
	| LCHIJA | cofhcore                | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| LCHIJA | cofhworld               | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | controlling             | 3.0.7                    | Controlling-3.0.7.jar                              | None                                     |
	| LCHIJA | craftingtweaks          | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
	| LCHIJA | craftpresence           | v1.5.5                   | CraftPresence-1.12.2-1.5.5.jar                     | eca02c6a597321ad22340897683951ba5c76720a |
	| LCHIJA | ctgui                   | 1.0.0                    | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
	| LCHIJA | crafttweakerjei         | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
	| LCHIJA | creeperconfetti         | 1.4.2                    | creeperconfetti-1.4.2.jar                          | None                                     |
	| LCHIJA | custommainmenu          | 2.0.9                    | CustomMainMenu-MC1.12.2-2.0.9.jar                  | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar                        | None                                     |
	| LCHIJA | defaultoptions          | 9.2.8                    | DefaultOptions_1.12.2-9.2.8.jar                    | None                                     |
	| LCHIJA | diethopper              | 1.1                      | diethopper-1.1.jar                                 | None                                     |
	| LCHIJA | naturescompass          | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
	| LCHIJA | refinedstorage          | 1.6.15                   | refinedstorage-1.6.15.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | mantle                  | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA | twilightforest          | 3.9.984                  | twilightforest-1.12.2-3.9.984-universal.jar        | None                                     |
	| LCHIJA | tconstruct              | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                   | None                                     |
	| LCHIJA | dym                     | 1.1.1                    | DocumentYourModMod-1.1.1.jar                       | None                                     |
	| LCHIJA | thermalfoundation       | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | draconicevolution       | 2.3.24                   | Draconic-Evolution-1.12.2-2.3.24.349-universal.jar | None                                     |
	| LCHIJA | dynamictrees            | 1.12.2-0.9.5             | DynamicTrees-1.12.2-0.9.5.jar                      | None                                     |
	| LCHIJA | traverse                | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                       | None                                     |
	| LCHIJA | dttraverse              | 1.5                      | dttraverse-1.5.jar                                 | None                                     |
	| LCHIJA | elevatorid              | 1.3.11                   | ElevatorMod-1.12.2-1.3.11.jar                      | None                                     |
	| LCHIJA | enderstorage            | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | fastfurnace             | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
	| LCHIJA | fastleafdecay           | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| LCHIJA | foamfix                 | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                          | None                                     |
	| LCHIJA | forgelin                | 1.8.3                    | Forgelin-1.8.3.jar                                 | None                                     |
	| LCHIJA | ftblib                  | 5.4.3.130                | FTBLib-5.4.3.130.jar                               | None                                     |
	| LCHIJA | ftbutilities            | 5.4.0.100                | FTBUtilities-5.4.0.100.jar                         | None                                     |
	| LCHIJA | itemfilters             | 1.0.3.12                 | ItemFilters-1.0.3.12.jar                           | None                                     |
	| LCHIJA | ftbquests               | 1.7.2.189                | FTBQuests-1.7.2.189.jar                            | None                                     |
	| LCHIJA | ftbacademymod           | 1.0.3.41                 | FTBAcademyMod-1.0.3.41.jar                         | None                                     |
	| LCHIJA | ftbbanners              | 1.1.0.11                 | FTBBanners-1.1.0.11.jar                            | None                                     |
	| LCHIJA | ftbguides               | 2.0.0.48                 | FTBGuides-2.0.0.48.jar                             | None                                     |
	| LCHIJA | ftbtutorialmod          | 1.0.0.5                  | FTBTutorialMod-1.0.0.5.jar                         | None                                     |
	| LCHIJA | ftbbackups              | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.5.jar                    | None                                     |
	| LCHIJA | gamestages              | 2.0.115                  | GameStages-1.12.2-2.0.115.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | harvestables            | 1.2                      | harvestables-1.2.1.jar                             | None                                     |
	| LCHIJA | hats                    | 7.0.0                    | Hats-1.12.2-7.0.2.jar                              | None                                     |
	| LCHIJA | teslacorelib            | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| LCHIJA | instrumentalmobs        | 1.1                      | Instrumental-Mobs-1.1.jar                          | None                                     |
	| LCHIJA | inventorytweaks         | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest               | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | jeresources             | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
	| LCHIJA | letsencryptcraft        | @VERSION@                | letsencryptcraft-1.10.2-1.2.0.jar                  | None                                     |
	| LCHIJA | reborncore              | 3.15.5.467               | RebornCore-1.12.2-3.15.5.467-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | mainmenuscale           | 1.0                      | MainMenuScale-1.3.2.jar                            | None                                     |
	| LCHIJA | minetogether            | unspecified              | minetogether-1.10.2-2.2.0-RC5.jar                  | None                                     |
	| LCHIJA | minetogetherserver      | unspecified              | minetogether-1.10.2-2.2.0-RC5.jar                  | None                                     |
	| LCHIJA | mob_grinding_utils      | 0.3.13                   | MobGrindingUtils-0.3.13.jar                        | None                                     |
	| LCHIJA | modnametooltip          | 1.10.1                   | modnametooltip_1.12.2-1.10.1.jar                   | None                                     |
	| LCHIJA | moreoverlays            | 1.15.1                   | moreoverlays-1.15.1-mc1.12.2.jar                   | None                                     |
	| LCHIJA | morpheus                | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
	| LCHIJA | mousetweaks             | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
	| LCHIJA | neat                    | 1.4-17                   | Neat 1.4-17.jar                                    | None                                     |
	| LCHIJA | netherportalfix         | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar                  | None                                     |
	| LCHIJA | oreexcavation           | 1.4.140                  | OreExcavation-1.4.140.jar                          | None                                     |
	| LCHIJA | projectintelligence     | 1.0.7                    | ProjectIntelligence-1.12.2-1.0.7.24-universal.jar  | None                                     |
	| LCHIJA | refinedstorageaddons    | 0.4.4                    | refinedstorageaddons-0.4.4.jar                     | None                                     |
	| LCHIJA | resourceloader          | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | resourcereloader        | 1.0.2.5                  | ResourceReloader-1.0.2.5.jar                       | None                                     |
	| LCHIJA | additionalstructures    | 2.2.2                    | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar   | None                                     |
	| LCHIJA | simplybackpacks         | 1.2.2                    | simplybackpacks-1.2.2.jar                          | None                                     |
	| LCHIJA | storagedrawers          | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
	| LCHIJA | sutils                  | 1.0                      | StructureUtils-1.1.0.4.jar                         | None                                     |
	| LCHIJA | tesslocator             | 1.1.0.15                 | Tesslocator-1.1.0.15.jar                           | None                                     |
	| LCHIJA | theoneprobe             | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                        | None                                     |
	| LCHIJA | thermalexpansion        | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalcultivation      | 0.3.3                    | ThermalCultivation-1.12.2-0.3.3.12-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics         | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | tinkertoolleveling      | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | tipthescales            | 1.0.4                    | TipTheScales-1.12.2-1.0.4.jar                      | None                                     |
	| LCHIJA | tombmanygraves          | 1.12-4.2.0               | TombManyGraves-1.12-4.2.0.jar                      | None                                     |
	| LCHIJA | topaddons               | 1.12.2-1.11.0            | topaddons-1.12.2-1.11.0.jar                        | None                                     |
	| LCHIJA | trumpetskeleton         | 1.12-1.0.2.1             | trumpetskeleton-1.12-1.0.2.1.jar                   | None                                     |
	| LCHIJA | xlfoodmod               | 1.12.2-1.9.2             | XL-Food-Mod-1.12.2-1.9.2.jar                       | None                                     |
	| LCHIJA | xpt                     | 2.0.1                    | XPTeleporters-1.12.2-2.0.1.jar                     | None                                     |
	| LCHIJA | orelib                  | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround               | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | phosphor-lighting       | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | reauth                  | 3.6.0                    | reauth-3.6.0.jar                                   | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| LCHIJA | teslacorelib_registries | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |

	Loaded coremods (and transformers): 
SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  pl.asie.splashanimation.core.SplashProgressTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.jar)
  bre.smoothfont.asm.Transformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
LoadingPlugin (splashlogofix-1.0.jar)
  me.modmuss50.splashlogofix.asm.ClassTransformer
StructureUtilsASM (StructureUtils-1.1.0.4.jar)
  me.modmuss50.structureutils.StructureTransformer
AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.3.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce RTX 2060/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.15.5.467
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 

* **Is it Repeatable?**: YES

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by aaronhowser1** [comment]
FTBTeam/FTB-Quests/issues/331
