### ISSUE TITLE
Domic resonator crafting not working

### ISSUE THREAD

**Issue by ricardopinto21** [FTBTeam/FTB-Academy#310]
modpak vesrion 1.2.0

prints:

I craft it:

![2020-07-01_15 33 57](https://user-images.githubusercontent.com/67697745/86256568-6288eb80-bbb0-11ea-909b-8e60b702862a.png)

but give me other item:

![2020-07-01_15 28 59](https://user-images.githubusercontent.com/67697745/86256075-c5c64e00-bbaf-11ea-9c1f-d9ca6f9fee5b.png)

**Comment by aaronhowser1** [comment]
Sneak right click on it to change modes.

**Comment by ricardopinto21** [comment]
thank you

**Comment by kubazpolanky** [comment]
Thank you so much
