### ISSUE TITLE
Luncher crush while loading

### ISSUE THREAD

**Issue by Sich06** [FTBTeam/FTB-Academy#311]
**Modpack Version**: 1.1.1

* **Issue**: The luncher crush while loading. The game says CraftPresence may be the cause.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/67e75b63

* **Is it Repeatable?**: YES

**Comment by aaronhowser1** [comment]
1.1.1 is unsupported, use 1.2 on the FTB App
