### ISSUE TITLE
After deleting a mod in this pack due to it not letting me start my world I got sent back to the academy

### ISSUE THREAD

**Issue by sharkshipgamer** [FTBTeam/FTB-Academy#312]
<!-
I deleted a mod from the pack because it wasn’t letting me load my world up but it sent me back to the academy, it didn’t reset any of my world except for my items and journeymap And the quests
* **Modpack Version**: 1.1.1

* **Issue**: <! I deleted mine together because it wasn’t letting me join my world but when I joined I was back in the academy with no quests completed even tho I had and no items in my inventory.

* **Link to Log or Crash File Paste**: <!-- I don’t have a crash file

* **Is it Repeatable?**: <!-- Probably if I reinstalled mine together 

* **Mod/s Affected**: <!-- mine together 

* **Known Fix**: <!- deleting mine together

**Comment by aaronhowser1** [comment]
1.1.1 is unsupported, use 1.2
