### ISSUE TITLE
"Injecting Burger directly into veins" quest does not complete

### ISSUE THREAD

**Issue by kalisture** [FTBTeam/FTB-Academy#318]
Using FTBApp

* **Modpack Version**: 1.2.0

* **Issue**: Quest "Injecting Burger directly into veins" states to craft a meat feeder, upon crafting a meat feeder, the quest is not complete. The quest is oddly greyed out in the quest menu

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

**Comment by aaronhowser1** [comment]
You haven't unlocked the quest yet then. Grey quests are locked, you have to do the prerequisites first

**Comment by kalisture** [comment]
> You haven't unlocked the quest yet then. Grey quests are locked, you have to do the prerequisites first

There does not seem to be any pre-requisites for the quest. There are no arrows pointing to it, and i have fulfilled every other quest that seems relevant. I am assuming pre-requisites are only within each tab.

**Comment by aaronhowser1** [comment]
Use the command `/ftbquests editing_mode`, then right click the quest and click Edit. Go down to Dependencies and see if there's anything there that you haven't completed.

Alternatively, you could update FTBQ to the latest version, that adds a button that shows all dependencies
![image](https://user-images.githubusercontent.com/15698722/88502528-5cf6a980-cf94-11ea-8563-7bd107656411.png)

**Comment by kalisture** [comment]
Thank you for your assistance, I will be closing this. 
There was an extra pre-requisite that wasn't evident, in "Bucket Filler".
Take care
