### ISSUE TITLE
[Suggestion] General Storage Clarification - Swap Iron Chests and Storage Crates text location on Banner

### ISSUE THREAD

**Issue by TomBombadil4Real** [FTBTeam/FTB-Academy#32]
* **Modpack Version**: 1.0.0

* **Issue**: This isn't an issue just more of a possible clarification to assist new users. Under the General Storage tutorial it says "Open the different tiers of Iron Chests and Storage Crates", Iron Chests appears above the crates and Storage Crates appears above the Iron Chests. Not a big issue but switching either the storage containers or the wording so they match up might help new users from possibly getting confused. 

![2019-08-25_18 06 14](https://user-images.githubusercontent.com/54515956/63657938-d58d2e80-c763-11e9-95fd-acee6df036cf.png)

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: N/A

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Basically make it read

> Open the different tiers of
> Storage Crate and Iron Chests

that way the words are above the arrows for that specific block

**Comment by aaronhowser1** [comment]
Alternatively, just swap the actual blocks themselves
