### ISSUE TITLE
apex hosting

### ISSUE THREAD

**Issue by mrspacefish** [FTBTeam/FTB-Academy#321]
I'm using apex hosting for a ftb academy with 1 friend. but when i use  twitch and launch ftb acadamy it says that its missing a lot of things and has old versions. what should I do?
![Screenshot (47)](https://user-images.githubusercontent.com/69353416/89650008-b1046680-d88f-11ea-95e3-e737ef22bbe4.png)

**Comment by aaronhowser1** [comment]
The Twitch version is unsupported, use the FTB App version, which it looks like Apex is using.
