### ISSUE TITLE
Unable to download FTB Academy from Twitch

### ISSUE THREAD

**Issue by Unknown7111** [FTBTeam/FTB-Academy#323]
I'm unable to download FTB Acedemy from Twitch. 

Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 226406 in database. Aborting installation.

**Comment by aaronhowser1** [comment]
Do not use Twitch.
