### ISSUE TITLE
Can't break blocks

### ISSUE THREAD

**Issue by dmreins** [FTBTeam/FTB-Academy#325]
* **Modpack Version**: 1.12.2

* **Issue**: I'm trying to play on a server with others, and cannot break any blocks.  

I logged in the first time, was able to get through the tutorial and load in to the overworld.  Something came up at home, so I went into a hut at spawn, and logged out.  

Upon logging back in, I was unable to open the hut door to exit.  Another player came and opened the door so I could exit.  I traveled several hundred blocks away from spawn.  I can kill mobs.  I can harvest crops from a village garden.  I cannot break or place blocks including grass, flowers, dirt, leaves, etc.  I cannot open doors. I cannot sleep. 

I have logged out and back in, I have uninstalled and reinstalled the modpack using the FTB installer, I have drowned myself in lava, hugged a creeper.. nothing helps :)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/3f88f87c

* **Is it Repeatable?**: I can't not repeat the issue :) 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
The modpack version is not 1.12.2, the MINECRAFT version is.

Empty your inventory and run the command `/quit_school`.
