### ISSUE TITLE
Fast Panorama

### ISSUE THREAD

**Issue by FM1864** [FTBTeam/FTB-Academy#329]
* **Modpack Version**: FTB Academy v 1.2.0

* **Issue**: What happened is when I went off of my world and back to the main screen, the panorama was faster than normal, and kept scrolling faster

* **Is it Repeatable?**: Possibly

* **Mod/s Affected**: quark

* **Known Fix**: restarting not the game, but the whole modlauncher

**Comment by aaronhowser1** [comment]
I think this might be an AMD thing, because of Fastcraft, I may be wrong though
