### ISSUE TITLE
Update in Curseforge site

### ISSUE THREAD

**Issue by Kimberly-dev** [FTBTeam/FTB-Academy#330]
on curseforge.com the modpack is out of date (1.1) and I see that it is already in 1.2, could you update?

**Comment by aaronhowser1** [comment]
No, FTB is in the process of leaving CurseForge https://www.reddit.com/r/feedthebeast/comments/df2b0l/on_the_31st_october_2019_the_partnership_between/

**Comment by aaronhowser1** [comment]
Im fairly sure that when you launch the first time on CF, it says this too
