### ISSUE TITLE
the modpack crashed if i try to start up the modpack

### ISSUE THREAD

**Issue by Bart0246810** [FTBTeam/FTB-Academy#334]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
You're going to have to give literally any information if you want us to be able to help.

**Comment by Bart0246810** [comment]
![image](https://user-images.githubusercontent.com/71723375/93915138-d813dc00-fd07-11ea-853c-447ea5784b64.png)

**Comment by Bart0246810** [comment]
if i start it up i get this message

**Comment by aaronhowser1** [comment]
Upload the crash report. It's in the modpack's folder under `/crash-reports/`.

**Comment by Bart0246810** [comment]
at the forum?

**Comment by Bart0246810** [comment]
where can i find it?

**Comment by Bart0246810** [comment]
i've got this massage with every modpack i try to start

**Comment by aaronhowser1** [comment]
What do you mean at the forum? Upload it here.

Though if it happens on all modpacks, it's almost definitely not an Academy problem. Maybe make an issue on the [FTB App's issue tracker](https://github.com/FTBTeam/FTB-App/issues/) instead.
