### ISSUE TITLE
Minetogether public list don't work

### ISSUE THREAD

**Issue by Helwyr** [FTBTeam/FTB-Academy#335]
* **Modpack Version**: 1.2.0

* **Issue**: Public server list don't work because new version of mod "minetogether" is required

* **Link to Log or Crash File Paste**: https://www.hostpic.org/images/2010112143120088.jpg

* **Is it Repeatable?**: yes, just try to join a public server, nothing

* **Mod/s Affected**: minetogether 2.2.1

* **Known Fix**: just updating last version of mod (MineTogether-1.12.2-2.3.6.jar)

**Comment by aaronhowser1** [comment]
Fixed in 1.4
