### ISSUE TITLE
TConstruct Hammer has major Block Breaking Lag with Stone and Netherrack

### ISSUE THREAD

**Issue by Crystallyne** [FTBTeam/FTB-Academy#336]
* **Modpack Version**: 1.2.0

* **Issue**: When using the Tinker's Construct Hammer to break regular stone and netherrack blocks, it takes a long time for the blocks to drop as items. If using it more than once, the 2nd strike will break one block at a time, in a spiral starting in the center. Sometimes it only breaks the center block and fails to break the rest of the blocks. You can see an example of the issue in a clip from my stream on Twitch: https://www.twitch.tv/kitherit/clip/CourageousDignifiedHyenaRuleFive

I have tried adjusting the dedicated RAM from 6GB to 8GB to 10GB and it never changes at all. I have tried loading the game with ONLY TConstruct and it's dependencies loaded, and it works just fine. I also have another friend playing the exact same modpack and he is having the exact same issue, though others on the same server or using the same modpack has not seen the issue. The Tinker's Construct Excavator does not have the same issue, and I can zip through sand all day long with zero lag. It is only the Hammer having the issue, and it only seems to happen with Stone/Cobblestone and Netherrack. I can break all other stone blocks just fine with the Hammer, and have zero block breaking lag. This definitely seems to be a conflict with another mod, but I've no idea how to troubleshoot it or identify the conflict.

* **Link to Log or Crash File Paste**: Unavailable

* **Is it Repeatable?**: Yes, I have tried a fresh install of the modpack with zero modifications made to it, and I still have this issue.

* **Mod/s Affected**: Tinker's Construct

* **Known Fix**: None Known

**Comment by aaronhowser1** [comment]
Update ftb ultimine

**Comment by Crystallyne** [comment]
Ooohhh THANK YOU!!! That 100% fixed the problem for me!

**Comment by Crystallyne** [comment]
So I'm reopening this because I would like to put in a request for the Ultimine mod to be updated on the FTB Launcher for FTB Academy. I'm playing on a server with a good sized group of people, and while we can update it server side, everyone else would have to update the mod as well. If it's part of the base FTB Academy modpack on the Launcher, I think it would automatically update for everyone? Or they can update it that way? Either way, it would help significantly.

**Comment by aaronhowser1** [comment]
Once University is released (which is very soon), I will update Academy.
