### ISSUE TITLE
Botania Tutorial : Cannot Bind Mana Spreader to Pool.

### ISSUE THREAD

**Issue by DigitalySane** [FTBTeam/FTB-Academy#337]
* **Modpack Version**: 1.3.0
* **Issue**: Botania mana spreader will not bind to mana pool in tutorial (assume in general as well?)

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Botania

* **Known Fix**: None

**Comment by aaronhowser1** [comment]
![](https://cdn.discordapp.com/attachments/613467918176616458/767461301889925180/unknown.png)

Works fine for me. Try reinstalling?

**Comment by PhantomZero2** [comment]
I have the same problem, i've reinstalled the modpack multiple times already and i can't get it working. Have also tried to skip the tutorial but it doesn't do anything either

**Comment by OmNomPandass** [comment]
I've been having this issue too since the update; i skipped the tutorial and teleported to the overworld (which i had to do via a nether portal in creative mode) and the mana spreader worked fine outside the tutorial
I also seem unable to pull the lever in the automation tutorial

**Comment by Drago5801** [comment]
Same problem here. Tried the method with the Nether portal as @OmNomPandass said, but if you quit und rejoin you start at the school again.

And it seems like KubeJS has an error with one script: https://pastebin.com/UZj7mPmk
Also "/quit_school" brings an error: https://pastebin.com/TAF8E6Mu

**Comment by TylesFNQ** [comment]
I have the same issue, tried reinstalling the mob pack still no luck.
It appears to me that the mana pool is locked and can't be interacted with (therefore selected with the wand). I got around this by going into creative and putting mana in using a mana tablet.
I then got the same issue with the /quit_school command not working.
