### ISSUE TITLE
I cant get out of school

### ISSUE THREAD

**Issue by Nightraven17472** [FTBTeam/FTB-Academy#338]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by TylesFNQ** [comment]
I have the same issue (also have the issue with the mana pool linking) my logs are in https://pastebin.com/t60RzDGF

it is happening with version 1.3.0 of the pack.
The problem wasn't fixed by removing and reinstalling the pack.
and I have tried multiple run thoughts and it occurs on each.

**Comment by WitherKing43** [comment]
I am also having this issue. as TylesFNQ stated, it is only happening on v. 1.3.0 and does not resolve when you re-install the pack or try different worlds.

**Comment by maxlerno1** [comment]
also have this issue problems start in the storage section when the quests skip upgrading the chest. problems continue when you complete filtering quest but can't flip lever. Also cant link mana pool so you get locked at the very end and then you get completely stuck when you try to reset school or quit it.

fixed this issue by deleting the version and then downloading the 1.2.0 parch.

**Comment by aaronhowser1** [comment]
Fixed in 1.4
