### ISSUE TITLE
i cant download the modpacks eevry single modpack i install is stuck on creating envoirment and when i try to start the modpack the launcher says unable to start minecraft

### ISSUE THREAD

**Issue by AngrySasukee** [FTBTeam/FTB-Academy#339]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by AngrySasukee** [comment]
i dk why i got muted i didnt troll btw but aight also yall are just crybabies wtf do i ned to do i never rlly used github,????

**Comment by AngrySasukee** [comment]
![Uploading image.png…]()

**Comment by aaronhowser1** [comment]
![](https://cdn.discordapp.com/attachments/613467918176616458/768021486236729354/unknown.png)

Reread the entire conversation, do what I said in it. You have no reason to continue talking on the Academy issue tracker, as it is not an Academy issue.
