### ISSUE TITLE
Player/ Camera Glitch

### ISSUE THREAD

**Issue by georgethomp8** [FTBTeam/FTB-Academy#34]
* **Modpack Version**: 

* **Issue**:  1.0.0

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: ] unkown

* **Known Fix** unkown

**Comment by TrueDakkon** [comment]
Yea this doesn't help but I do have the glitch and it essentially is when you move your camera freaks out and shoots around all over the place essentially forcing you to see nothing but black. I have noticed when in my inventory my player model is also freaking out. I have tried closing and reloading the world, but after a couple of steps the glitch kicked in again.

**Comment by Sunekaer** [comment]
Reset your BetterFPS settings, by deleting betterfps.json in the config folder
