### ISSUE TITLE
Can't skip tutorial

### ISSUE THREAD

**Issue by Sinfulcola** [FTBTeam/FTB-Academy#340]
* **Modpack Version**: 1.3.0

* **Issue**: When skipping the tutorial, text log shows "Sinfulcola has graduated!"
"An unknown error occurred while attempting to perform this command"
When loading into the tutorial, there's a warning in the text log that says "Error in kubejs/detectors.js"

* **Link to Log or Crash File Paste**: I'm just a minecraft player, I have no idea how to do this dude

* **Is it Repeatable?**: Happens every time I try to skip the tutorial

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Update to 1.4
