### ISSUE TITLE
Storage Quest Unchecked

### ISSUE THREAD

**Issue by CesarUlises1996** [FTBTeam/FTB-Academy#341]
* **Modpack Version**: 1.1.1

* **Issue**: i have completed all quest from "Storage" but this isn't checked

https://github.com/CesarUlises1996/Bugs/blob/master/Storage%20Quest.png?raw=true

 I just restart the game, trying to update the quest but still doesn't work

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by BanHerobrine** [comment]
Yeah me to I go into the storage room, open the boxes and then get the upgrader. I right click on it and the wooden chest is now an iron chest. but the quest says the I did do it. can someone help me out here? Thanks.
