### ISSUE TITLE
Industrial Foregoing fluid pump not working

### ISSUE THREAD

**Issue by Shenanihands** [FTBTeam/FTB-Academy#343]
So whenever I tried using the Fluid pump from IF, it would not work regardless of the source block on lava it was placed on, or the range upgrade or the power source. If it did work, it would pump like 2000 mb of lava, then stop and not work again. I tried troubleshooting it, and I even asked the mods on the FTB discord, but it did not want to work. I'm not sure if it is a bug, or specifically gated behind a quest.

**Comment by Grocel** [comment]
I had the same issue today. I was able to fix it by mine and replace the machine. but for me this fix only lasts until the next server/single-player restart.
