### ISSUE TITLE
in school: upgrading from wooden chest to iron chest quest not working

### ISSUE THREAD

**Issue by BanHerobrine** [FTBTeam/FTB-Academy#345]
In school  I go into the storage room, open the boxes and then get the upgrader. I right click on it and the wooden chest is now an iron chest. but the quest says the I did do it. can someone help me out here? Thanks.

Modpack Version: 1.12.2
* **Issue**: Look above

* **Link to Log or Crash File Paste**: there are none

* **Is it Repeatable?**: i cant do anything about it its doing it every time

* **Mod/s Affected**: iron chests, ftb quests

* **Known Fix**: i dont know what to do about it

**Comment by aaronhowser1** [comment]
Update to 1.4

**Comment by BanHerobrine** [comment]
but the modpack is on 1.12.2?

**Comment by aaronhowser1** [comment]
Update to Academy version 1.4
