### ISSUE TITLE
Title screen background, mob and player animations do not animate properly.

### ISSUE THREAD

**Issue by ziggythomas1123** [FTBTeam/FTB-Academy#347]
* **Version**: FTB Academy 1.4

* **Issue**: The background camera panning in the title screen, mob animations, and player animations + camera aren't functioning normally. I can't come up with a thing to describe it as other than "spazzy." The legs/arms of mobs and players flail all over the place, even when standing still, very much like those joke gmod animations. The camera, when "View Bobbing" is turned on, also flails about while moving, so terrain is only visible when standing still. It doesn't do this when swimming in water for some reason.
The Title screen background also pans vertically, sometimes extremely quickly.

          I should also mention that my computer was extremely hot when this issue occurred. It may be a 
          hardware temperature issue causing some value to become corrupted. This may be a false alarm,
          but it is a problem nonetheless, and I figured i should talk about it.

* **Link to Log or Crash File Paste**: 
[debug.log](https://github.com/FTBTeam/FTB-Academy/files/5461628/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Academy/files/5461630/latest.log)
I do not know o=if these are correct. Please let me know if they aren't.

* **Is it Repeatable?**: The issue is repeatable. It is immediately visible on seeing the title screen.

*I do not know what in the code might be causing these glitches, but my computer was extremely hot. The temperature might have been the problem, but I don't understand why the animations would bug out like this.

* **Edit**: I let my computer cool, and re-launched the game. The title screen was panning vertically extremely fast.  I do not believe it's a temperature issue.

**Comment by aaronhowser1** [comment]
IIRC, this is something to do with BetterFPS, or maybe VanillaFix. Something to do with AMD, I think. Remove BetterFPS, see if it gets fixed.

**Comment by aaronhowser1** [comment]
https://www.youtube.com/watch?v=DiuBQ_P5Sms

Looks like you can just switch BFPS to use a different Algorithm instead

**Comment by ziggythomas1123** [comment]
Thank you! This helped a lot!

> https://www.youtube.com/watch?v=DiuBQ_P5Sms
> 
> Looks like you can just switch BFPS to use a different Algorithm instead
