### ISSUE TITLE
Server Crashes on startup

### ISSUE THREAD

**Issue by CodeMastr3** [FTBTeam/FTB-Academy#351]
* **Modpack Version**: 1.4

* **Issue**: Server crashes on startup I have installed it multiple times. It used to work but no longer

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/7dc89b47

* **Is it Repeatable?**: Happens every time I boot it up

**Comment by Sunekaer** [comment]
Looks like your missing a lot of mods, try  and run the server installer again
