### ISSUE TITLE
Botanical Apothecary will not take my seeds, cannot progress

### ISSUE THREAD

**Issue by vfales** [FTBTeam/FTB-Academy#353]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Does it have water in it

**Comment by frankie738** [comment]
I am having the same issue and mine does have water in it

**Comment by vfales** [comment]
Same mine has water and took everything but the seeds

Best,
Vanessa Fales
________________________________

**Comment by aaronhowser1** [comment]
Are you sure your recipe is correct? Hovering over it should show a thing over the crosshair that has seeds. Can you post a screenshot of you looking at it

**Comment by frankie738** [comment]
![image](https://user-images.githubusercontent.com/75406850/101431735-119ec100-38cd-11eb-97a2-a14f2d5217b1.png)

**Comment by frankie738** [comment]
![image](https://user-images.githubusercontent.com/75406850/101431772-267b5480-38cd-11eb-82e5-5b2c59f8bc9b.png)

**Comment by frankie738** [comment]
![image](https://user-images.githubusercontent.com/75406850/101434549-5d069e80-38d0-11eb-9fab-9b82f78f0bf8.png)
I put in the flower petals and the I try to through in the seeds and they just float there and if I click nothing happens

**Comment by frankie738** [comment]
and I've tried resetting the tutorial and it does the same thing

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/101464132-e1264980-3903-11eb-90d9-3198ad362fc6.png)
This is what it should show over your crosshair. Can you show the inside of it as well?

Also, you can skip the school with `/quit_school` if necessary.

**Comment by likeaknife** [comment]
This drove me nuts, I restarted the academy like 8 times before I got it to work. Rightclicking is actually placing the petals in the ground - and then you can't dig them up. What you're supposed to do is DROP the items in with Q (Default bind). I hope this helps!
