### ISSUE TITLE
Dynamo doesn’t give his power out 

### ISSUE THREAD

**Issue by xPandoPvP** [FTBTeam/FTB-Academy#355]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
As the quest says (I think), it only outputs energy if it can generate energy.

Also, energy comes out of the thin bit.

**Comment by xPandoPvP** [comment]
It doesnt  give Power out when it already got Power or is producing power
