### ISSUE TITLE
Minecraft crashes when playing LifeInTheVillage2 mod using CurseForge

### ISSUE THREAD

**Issue by alan-czajkowski** [FTBTeam/FTB-Academy#356]
**Modpack Version**:
* see crash file link

**Issue**:
* trying to play Life in the village 2 mod using CurseForge, Minecraft crashes during regular play, nothing special is happening when it crashes (just while normal building or destroying gameplay)

**Link to Log or Crash File Paste**:
* https://paste.feed-the-beast.com/view/8ea40b32

**Is it Repeatable?**:
* game always crashes after a few mins of play

**Mod/s Affected**:
* Life in the village 2 - v1.10a (using CurseForge v0.0.20)

**Known Fix**:
* none

**Comment by aaronhowser1** [comment]
Why the absolute hell are you putting this here? This is the issue tracker for FTB Academy.
