### ISSUE TITLE
MoreOverlays crashes FTBAcademy on server

### ISSUE THREAD

**Issue by CaidenKehrer** [FTBTeam/FTB-Academy#360]
* **Modpack Version**: ftb academy 1.1.1-1.12.2 -(release)

* **Issue**: More overlays causes crash on server
* 
* **Link to Log or Crash File Paste**:https://paste.feed-the-beast.com/view/2520a4ab

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: MoreOverlays

* **Known Fix**: going to single player world and turning more overlays off then going back into multiplayer world and never turning it back on.

**Comment by aaronhowser1** [comment]
Update the pack using FTB App. We do not support the Curseforge version.
