### ISSUE TITLE
After pressing the wood to iron update in storage it doesn't let me continue playing.

### ISSUE THREAD

**Issue by EclipseMoon176** [FTBTeam/FTB-Academy#367]
* **Modpack Version**: 1.1.1

* **Issue**: i pressed the update on the chest and it didn't finish the task and it didn't let me move on to other tasks.

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: yes it is i tried multiple times  

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Stop using the Curseforge version.
