### ISSUE TITLE
No server file for ftb academy latest version

### ISSUE THREAD

**Issue by Ledinis** [FTBTeam/FTB-Academy#368]
* **Modpack Version**:  FTBAcademy-1.1.1

* **Issue**: The FTB Academy version is 1.1.1 but the server file is 1.0.0, we can't play with friends if i would want to host the server 

* **Link to Log or Crash File Paste**: https://imgur.com/GkSBgqn

* **Is it Repeatable?**: Yea..

* **Mod/s Affected**: FTB Academy version 1.1.1 server file version 1.0.0

* **Known Fix**:

**Comment by aaronhowser1** [comment]
You closed this so I assume you figured it out, but FTB does not support Curseforge versions of our packs any more. Use the FTB App, which has several updates not on CF and also server files
