### ISSUE TITLE
Moving items inside your inventory drops them

### ISSUE THREAD

**Issue by Pitva** [FTBTeam/FTB-Academy#369]
* **1.4.0**:

* **While in a server every time I opened my inventory and left-clicked on an item to either move it or craft something it would just drop it on the ground. This happened only to me, not to anyone else on the server**

* **It randomly comes and goes, there isn't anything triggering it**: 

* **Open crafting tables and chest a few times and sometimes it goes away on its own**:

**Comment by aaronhowser1** [comment]
Spam shift, alt, and control, the game thinks one of those is being pressed
