### ISSUE TITLE
[bug] wither builder (industrial foregoin) not place block

### ISSUE THREAD

**Issue by Dheumanizer** [FTBTeam/FTB-Academy#373]
wither builder (industrial foregoin) not place block:
![immagine](https://user-images.githubusercontent.com/27067756/126896404-07346a3a-7a65-48e5-abe1-7980c370efef.png)

energy full, redstone ignore.

* **Modpack Version**: 1.1.0 (latest) -->

* **Issue**: Industrial Foregoing Wither Builder not work: not place block (soul sand and skull)

**Comment by aaronhowser1** [comment]
This is the github for Academy 1.12. Post any 1.16 issues here: https://www.feed-the-beast.com/support
