### ISSUE TITLE
[bug] Cyclic debug messages spammed in server console log; Fixed in Cyclic-1.16.5-1.3.4.jar

### ISSUE THREAD

**Issue by legitswitch** [FTBTeam/FTB-Academy#374]
**Mod & Pack version**
FTB-Academy 1.16 v1.10

**How to reproduce the issue**
Look at console on server while playing with other people. The following message is repeated.

**A screenshot, if applicable**
Server thread/ERROR23:35:37
Cyclic PlayerEvent.SaveToFile{inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}

**Anything else we should know?**
This is fixed in the latest Cyclic release: Cyclic-1.16.5-1.3.4.jar

**Comment by aaronhowser1** [comment]
This is the support for Academy 1.12. 1.16 issues go here: https://www.feed-the-beast.com/support
