### ISSUE TITLE
Daytime and nighttime are happning at the wrong times.

### ISSUE THREAD

**Issue by MikaelS111** [FTBTeam/FTB-Academy#40]
* **Modpack Version**: 	FTBAcademy-1.0.0-1.12.2

* **Issue**: After the tutorial when you go into the overworld, the daytime and nighttime is happening at the wrong times.

Daytime starts at 00:00 and nighttime starts at 11:30 with sunset appearing around 10:00.

I've attached screenshots that show the times.

* **Link to Log or Crash File Paste**: No crashes or log.

* **Is it Repeatable?**: Yes. It happens on all saves in Single Player

* **Mod/s Affected**:  None

* **Known Fix**: No idea how to fix this.

![2019-08-27_18 24 41](https://user-images.githubusercontent.com/15056341/63789774-511fe480-c8f8-11e9-9a05-ac01aa047202.png)

![2019-08-27_18 11 04](https://user-images.githubusercontent.com/15056341/63789810-65fc7800-c8f8-11e9-95f4-80cc6c2d4e70.png)

![2019-08-27_18 26 00](https://user-images.githubusercontent.com/15056341/63789886-8cbaae80-c8f8-11e9-849d-a24b0bab35aa.png)

**Comment by Sunekaer** [comment]
Should be fixed in newest version, else theres nothing we can do about it
