### ISSUE TITLE
Friend joining on LAN causing Quests to reset

### ISSUE THREAD

**Issue by calebjway** [FTBTeam/FTB-Academy#45]
* **Modpack Version**: 1.0.0

* **Issue**: A friend who is joining me on LAN who has already played will occasionally join and the game will act like they have never joined before. This causes them to lose their entire inventory and to reset our game progress to back at the academy.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/76e7c76f

* **Is it Repeatable?**: It has happened 3 times now but I am unsure of the cause.

* **Mod/s Affected**: Questing mod?

* **Known Fix**: Nothing. The game seems to read the other player as a new user. We have had to restart 3 times and we are not wanting to start again.

**Comment by LatvianModder** [comment]
LAN is so awful in mc. There are extreme bugs in vanilla even, where there is a 50% chance you will crash when you quit lan game, noone knows cause. Maybe this is part of that group of super weird issues

**Comment by aaronhowser1** [comment]
Maybe it's something to do with Teams, because you're leaving the singleplayer team

**Comment by 1999jrj** [comment]
This problem also occurs over normal multiplayer, not just LAN. I have a server and every time players join each other's team, regardless of whether they've completed all the previous quests, all players quests get reset to the beginning of the school tutorial when unable to access the school anymore. Please help.
