### ISSUE TITLE
Replace Crates in Tech room with chests?

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Academy#47]
Could use 3 different Quark chests on the right, so it would show that those exist.

Would need to retake screenshot for Banners

**Comment by Sunekaer** [comment]
nah i think its fine as it is just the text there need that swapping of crate and chest

**Comment by aaronhowser1** [comment]
Different room, I'm talking about the tech/automation room

**Comment by Sunekaer** [comment]
okay then i dont care but its lowest prior
