### ISSUE TITLE
Fluid xfr quest bug

### ISSUE THREAD

**Issue by toruPuchuu** [FTBTeam/FTB-Academy#5]
I picked up the fluid tanks (shift-right click w/wrench), but I can't place them back down to complete the fluid tank quest. 

* **Modpack Version**: 1.0.0-1.12.2 

* **Issue**: I picked up the fluid tanks (shift-right click w/wrench), but I can't place them back down to complete the fluid tank quest. 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  yes 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
You aren't supposed to pick up the tank. There's a button at the top left of the inventory that allows you to reset the school, or skip to the overworld.

We wanted to have a thing that tells you to do this if this happens, but it currently isn't possible in FTB Quests

**Comment by aaronhowser1** [comment]
We're working on making it so that you simply *can't* sneak click the wrench on the tank during the school, so this can't happen
