### ISSUE TITLE
[please add] Cooking for Blockheads

### ISSUE THREAD

**Issue by iamweirdie** [FTBTeam/FTB-Academy#59]
https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads

The academy pack already includes the XL Food mod, requiring players to think about how to mix and match their foods for optimal meals. Cooking for Blockheads helps alleviate this process by showing what a player can make based on their inventory or what's stored in the kitchen that they build using the blocks from this mod.
Without this mod, players are left with an unorganized buffet of foods, where they randomly pick and choose from a pile of foods they've stocked up. Doing so makes the meal choice and creation process really annoying and tedious, not to mention quite a bit inefficient.

**Comment by loneztar** [comment]
Academy is an introduction to basic mods, as such, XL food fits very well. Cooking for Blockheads would be a perfect addition to a follow-on pack (if one were to occur) but rather a lot of hassle to explain for this pack so I can see why it was left out.

**Comment by iamweirdie** [comment]
Right, but the xl food mod is a bit cluttered by itself, as with any large food mod. I understand that explanation may SEEM like a hassle, but the mod is actually well documented.

http://blay09.net/mods/cookingforblockheads/?page=cookingforblockheads

**Comment by loneztar** [comment]
XL food isn't a large food mod - Pam's is a large food mod. CFB is great when you already have an understanding of those types of mods, not so much for really green players (I've had to explain CFB to dozens of vanilla veterans that haven't even got a clue about what a multiblock structure is). I can definitely see the value of the mod in a follow-up pack though. Decoration blocks are 99% necessary btw.

**Comment by Sunekaer** [comment]
Cooking for Blockheads wont be added.
