### ISSUE TITLE
mana pool tutorial glitch 

### ISSUE THREAD

**Issue by Trackvis** [FTBTeam/FTB-Academy#6]
I was having trouble in the Botania tutorial. After i get the Endoflame, and try to put mana into the mana pool from the mana Spreader, the mana doesn't go into the mana pool, i can't even complete the tutorial now and am stuck.

**Comment by Slimmer556** [comment]
I'm having the same issue. I feel like there must be a step I'm missing.

**Comment by Trackvis** [comment]
i have figured it out, you much place the endoflame on the lightest bit of grass behind the structure you make the endoflame from. once you place the endoflame, throw some coal/charcoal near it and wait a second or two and it should work.

**Comment by Slimmer556** [comment]
Oh wow, that was definitely my problem. I tried getting the charcoal to react with the endoflame but I didn't even think about dropping it. Thanks for coming back with the update.
