### ISSUE TITLE
Make AS Structure rewards team rewards

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Academy#63]

**Comment by aaronhowser1** [comment]
Also, maybe make it so you only get the blocks required to upgrade the structure, instead of the everything

**Comment by Venom31** [comment]
The upgrade idea is very good. That will actually make it _easier_, since player(s) won't have to track old and new number of blocks if they like to keep exactly the needed amount in their inventory.

**Comment by aaronhowser1** [comment]
I've done this and also made it so the reward is a named chest with the
contents saved. That lets you know it isn't just a bunch of random items,
and also it's all in one reward.
