### ISSUE TITLE
Enderchest quest gets completed when claiming the Endertank-quest-reward and vice versa

### ISSUE THREAD

**Issue by Cheos137** [FTBTeam/FTB-Academy#65]
* **Modpack Version**: 1.0.0

* **Issue**: the title discribes the whole bug

* **Link to Log or Crash File Paste**: no crash, no report

* **Is it Repeatable?**: yes, fully repeatable

* **Mod/s Affected**: null

* **Known Fix**: uuuh... well... i have no idea :)

**Comment by Sunekaer** [comment]
#25
