### ISSUE TITLE
error while downloading "Timeout attempting to download: https://edge.forgecdn.net/files/2766/338/FTBAcademy-1.0.0-1.12.2.zip"

### ISSUE THREAD

**Issue by giopalaga** [FTBTeam/FTB-Academy#67]
* **Modpack Version**:latest i guess? 8/20/19 release date 

* **Issue**: while downloading the issue appears 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: all

* **Known Fix**havent found any fixes:

**Comment by aaronhowser1** [comment]
Are you using a Mac by chance?

**Comment by Sunekaer** [comment]
Not something we can do anything about, either your pc problem or launcher your using

**Comment by giopalaga** [comment]
> Not something we can do anything about, either your pc problem or launcher your using

nice

**Comment by aaronhowser1** [comment]
It's unfortunate but it's the truth. Twitch just does that sometimes. Hopefully when the next update comes out, it'll work correctly and all these bugs will be ironed out. It's basically left to chance on our end though, we have no power over this.
