### ISSUE TITLE
Smeltery Tinkers quest stuck

### ISSUE THREAD

**Issue by diego898** [FTBTeam/FTB-Academy#68]
* **Modpack Version**: 1.0.0

* **Issue**: I cant complete the last part of the smeltery tinkers quest in the overworld - getting 18 seared bricks. Im stuck at 9/18, even though Ive made many more seared bricks both through cooking grout, and smelting cobblestone. 

* **Mod/s Affected**: Tinkers

**Comment by aaronhowser1** [comment]
They all have to be in your inventory at the same time
