### ISSUE TITLE
Seed duplication

### ISSUE THREAD

**Issue by Daviid000** [FTBTeam/FTB-Academy#73]
Modpack Version: 1.0.0

Issue: Seed duplication. When you plant an XL food seed break replant break replant again and again it duplicates the seeds. Very annoying when i want to move my farm but i get all these extra seeds by "cheating".

Link to Log or Crash File Paste: None

Is it Repeatable?: Yes

Mod/s Affected: XL food mod

Known Fix: IDK

Note: First issue posted so let me know if i missed anything

**Comment by Sunekaer** [comment]
From my short testing it's not a 100% chance that you get that extra seed?
you need to use left click to remove the seed, right harvest and auto replants the seed

**Comment by Daviid000** [comment]
Yea its not 100% of the time. But you do get seeds out of nowhere

**Comment by Sunekaer** [comment]
yeah thats fine
