### ISSUE TITLE
Impossible to localize the title of Astral Sorcery and Transportation chapters in the quest book because of wrong format

### ISSUE THREAD

**Issue by Dai-JiaLin** [FTBTeam/FTB-Academy#92]
* **Modpack Version**: 1.0.0

* **Issue**: It seems that you've used "Astral Sorcery" as title of the Astral Sorcery chapter in quest book instead of "{academy.astralsorcery.title}" which is in the same form used in other chapters' title. And the same problem exists in the transportation chapter.  It disables the localization for those two titles.

* **Is it Repeatable?**: yes

* **Known Fix**: You may just use "{academy.astralsorcery.title}" as title and add an entry in the .lang file to fix this problem. Thanks!

**Comment by aaronhowser1** [comment]
Whoops! We'll fix that. Just use `academy.astralsorcery.title` and `academy.transportation.title`, that's what they'll be in the next update.
