### ISSUE TITLE
Server missing some blocks

### ISSUE THREAD

**Issue by karlji** [FTBTeam/FTB-Academy#95]
* **Modpack Version**:1.00

* **Issue**: I tried to launch FTB Academy server to be able to play with my friend. I downloaded server pack from Twitch and used install batch file. I then moved all those files to my remote server and launched it. It launched without giving me an error in the console, however, some blocks are not working properly. I believe it is related to chisel because chiseled blocks just disappear upon placing within 1 sec. When I place regular block e.g. stone and then use a chisel, it is not changing it to chiseled blocks. I am not sure where the issue is, but it works for me on single player.

* **Link to Log or Crash File Paste**: The game is not crashing.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Chisel

* **Known Fix**: NA

**Comment by aaronhowser1** [comment]
Check to make sure Chisel is installed on the server.

**Comment by karlji** [comment]
> 
> 
> Check to make sure Chisel is installed on the server.

Can you please give me a hint how to do that? I have not hosted a server for at least 7 years, so I am a bit lost in the process to be honest :)

**Comment by aaronhowser1** [comment]
Open the server's `mods` folder, and look for a file that starts with Chisel.

Although, I just read the issue again and apparently you can craft Chisels, which means the mod is installed. Hmm, im not sure in that case then. Try restarting the server maybe.

**Comment by karlji** [comment]
> 
> 
> Open the server's `mods` folder, and look for a file that starts with Chisel.
> 
> Although, I just read the issue again and apparently you can craft Chisels, which means the mod is installed. Hmm, im not sure in that case then. Try restarting the server maybe.

Yes, I can see chisel, I can even use it. I can see a chiseled block in item menus as well. I just can't place those block as they immediately disappear and if I try to chisel regular block into this, it doesn't do anything. I will try to delete all server files and install it again and I will send a comment once I get home.

**Comment by karlji** [comment]
So I reinstalled the server. I did exactly the same as before and now it works. I have no idea what happened. I am closing this comment, it was apparently issued on my side. Apologies for spam.
