### ISSUE TITLE
Images and text translations not working

### ISSUE THREAD

**Issue by Maxfast** [FTBTeam/FTB-Academy#97]
Hello there,

today I installed the modpack on a nitrado server with forge preinstalled,
and copied all the mods also in the normal forge minecraft client mods folder in '.minecraft'.
Please tell me if I did something wrong that can be related to the issue I will explain now
The Modpack version is the 1.12.2 1.0.0 FTB Academy server version.
Everything is on MC 1.12.2 so there should be no issue with the version .

I logged in into the server and there was a warning already. It is saying 'Tutorial failed to load'.
After pressing esc and back into game again, I was able to spawn in the area where I had to do the beginner quests. I already noticed that some pictures on the walls could not be loaded so instead of an image there were black and purple colors on it which means the block has no texture as I know. This made it nearly impossible to to do the tutorial properly. The second issue is, that  the Achievement book you have in your first slot can't show you specific texts which try to explain you the function of items etc. It only says for example :  'ironchest.text1' .

After this message I am going to reinstall the modpack on the same server by removing all data before.

In my case I don't really know which mod causes the issue because I am a beginner 
But I think I did everything right during the installation process of the modpack and forge.

I don't know how to fix the problem.

If it will work in a few hours I will edit this post so you know it all worked well

Max

Max

**Comment by aaronhowser1** [comment]
Reinstall your modpack, it didn't download or install anything in the resources folder apparently. Either that, or the mod ResourceLoader isn't installed or working.

**Comment by Maxfast** [comment]
ok thank you! 
I am already reinstalling everything.
Is there a special installation guide for these modpacks ??
If the issue will show up again I will come back to you.

Thx a lot
 Max

**Comment by aaronhowser1** [comment]
You're supposed to use [Twitch](https://www.twitch.tv/downloads) to install modpacks. [Here's a guide to how to do that if you don't already know](https://help.twitch.tv/s/article/guide-to-modpacks?language=en_US).

**Comment by Maxfast** [comment]
i never knew that , how should that work ? Is it the same as a simple upload process?

**Comment by aaronhowser1** [comment]
How did you install the modpack, if not with Twitch? Did you use MultiMC or the old FTB Launcher? If you're using the old FTB Launcher, I suggest moving to Twitch or MultiMC, the FTB Launcher is old and supported and very buggy

**Comment by Maxfast** [comment]
NItrado is a server hosting company that is renting servers. I got one and on their website you can easily manage to download a forge server profile straight in the server files. After that I downloaded the Server Modpack and put the files per FTP in the folder minecraftotherpacks on the server. Some files ahd to be overwritten but the mods were working ?!

**Comment by Maxfast** [comment]
After a reinstall everything worked well, and I noticed that it was necessary to drag also the whole server modpack in the    .minecraft.  folder so I was able to see a completely new home screen.
